### ISSUE TITLE
Custom Scalar "LocalDateTime" is not working in Gateway

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/graphql-platform#4682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I've added a custom scalar to one of my micro services. when I added this micro to gateway,got an error like "Unable to resolve type reference `Input: LocalDateTime`. (HotChocolate.Types.InputObjectType)".

Adding the custom scalar to gateway also does'nt resolve it. But it worked fine as separate micro service.

Any way to fix this?

### Steps to reproduce

1. Added custom scalar in micro service as below in startup :
```
            .AddType<HotChocolate.Types.NodaTime.LocalDateTimeType>()
            .BindRuntimeType<DateTime, LocalDateTimeType>()                
            .AddTypeConverter<DateTime, LocalDateTime>(x => LocalDateTime.FromDateTime(x))
```

2. In gateway,added LocalDateTime scalar like :

```
           service.AddGraphQLServer("web")
                       .AddType<LocalDateTimeType>()
                        .AddRemoteSchema(service["svc"], ignoreRootTypes: false);
```

### Relevant log output

```shell
info: System.Net.Http.HttpClient.PSOAPI.LogicalHandler[100]
      Start processing HTTP request POST http://localhost:5000/psoapi
info: System.Net.Http.HttpClient.PSOAPI.ClientHandler[100]
      Sending HTTP request POST http://localhost:5000/psoapi
info: System.Net.Http.HttpClient.PSOAPI.ClientHandler[101]
      Received HTTP response after 19.5542ms - OK
info: System.Net.Http.HttpClient.PSOAPI.LogicalHandler[101]
      End processing HTTP request after 25.8079ms - OK
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `Input: LocalDateTime`. (HotChocolate.Types.InputObjectType)

   at HotChocolate.Configuration.TypeCompletionContext.GetType[T](ITypeReference typeRef)
   at HotChocolate.Types.FieldBase`2.OnCompleteField(ITypeCompletionContext context, TDefinition definition)
   at HotChocolate.Types.InputField.OnCompleteField(ITypeCompletionContext context, InputFieldDefinition definition)
   at HotChocolate.Types.FieldBase`2.CompleteField(ITypeCompletionContext context)
   at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ITypeCompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields)
   at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|31_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

11.3.8 & 12.5.0

**Comment by Sangeetha-Murugesan** [comment]
Thanks @benmccallum. It works !!

But do we need to explicitly add custom scalars for each micro service in gateway?.

**Comment by Sangeetha-Murugesan** [comment]
[Dummy comment to prevent the stale bot from closing the issue]

**Comment by PascalSenn** [comment]
you also need to register it on the internal representation of downstream schema on the gateway:
```csharp
service.AddGraphQLServer("web")
    .AddType<LocalDateTimeType>()
    .AddRemoteSchema(service["svc"], ignoreRootTypes: false);


services
    .AddGraphQL("svc")
    .AddType<LocalDateTimeType>()

```

In 13 this will be automatic

**Comment by Sangeetha-Murugesan** [comment]
hi @PascalSenn , this workaround is working fine until 11.3.8 , when I am trying to upgrade to version 12.10.0, I am getting the following error:  
_"An item with the same key has already been added. Key: BigInt"_  (I have added this custom scalar in all of my downstream schemas) .

 If I removed this scalar from my downstream schemas , am getting another error saying **"The name `TaskReqInput` was already registered by another type. (HotChocolate.Types.InputObjectType)"**  , but this type is defined only once in one of my schema.
 
I have registered schema in this way:


		```
                  service_coll.AddGraphQLServer("web")
                   .AddType<HotChocolate.Types.NodaTime.LocalDateTimeType>()
                   .AddType<LongType>()
                   .AddType<AnyType>()
                   //.AddType(new LongType("BigInt"))
                   .AddFiltering()
                   .SetRequestOptions(_ => new HotChocolate.Execution.Options.RequestExecutorOptions { ExecutionTimeout = TimeSpan.FromMinutes(10) });
				   
		var Gservices = //list of downstream services;
				   
	         foreach (var svc in Gservices)
                {
                    var service = JsonConvert.DeserializeObject<Dictionary<string, string>>(svc);

                    service_coll.AddGraphQLServer("web").InitializeOnStartup().PublishSchemaDefinition(c => c.SetName(service["svc"]));

                    service_coll.AddHttpClient(service["svc"], (sp, client) =>
                    { 
                        client.BaseAddress = new Uri(service["ep"]);  
                    });

                    service_coll.AddGraphQLServer("web").AddHttpRequestInterceptor<HttpRequestInterceptor>()
                        .AddRemoteSchema(service["svc"], ignoreRootTypes: false);


                    service_coll.AddGraphQL(service["svc"])
                    .AddType<HotChocolate.Types.NodaTime.LocalDateTimeType>()
                    .AddType<LongType>().AddType<AnyType>()
                  //.AddType(new LongType("BigInt"))
                        ;
                }
```

```

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.

You can join the preview of Hot Chocolate Fusion now on Slack
