### ISSUE TITLE
UseProjections in Combination with BindMember throws Exception

### ISSUE THREAD

**Issue by BickelLukas** [ChilliCream/graphql-platform#5054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Model 
```cs
class Item
{
    public string Subject { get; set; }
    public string User { get; set; }
}

class User 
{
    public string Username { get; set; }
}
```

Query 
```cs
class Query 
{
    [UseOffsetPaging]
    [UseProjection]
    public IQueryable<Item> GetItems(IAsyncDocumentSession session)
    {
        return session.Query<Item>();
    }
}
```

Type Extension
```cs
[ExtendObjectType(typeof(Item))]
public class ItemTypeExtension
{
    [BindMember(nameof(Item.User))]
    public async Task<User> GetUser([Parent] Item item,  IAsyncDocumentSession session)
        => await session.LoadAsync<User>(item.User);
}
```

---
When querying for items and the projection visitor throws an exception when the user is queried:
The follwing works 
```gql
query {
  items {
    subject
  }
}
```

This throws the following exception `Property 'System.String Username' is not defined for type 'System.String' (Parameter 'property')`
```gql
query {
  items {
    subject
    user {
      username
    }
  }
}
```

### Steps to reproduce

https://github.com/glen-84/hc-5054 (.NET 8, HC 14.0.0-rc.1)

1. Use the above code and execute the query

### Relevant log output

```shell
at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at HotChocolate.Data.Projections.Expressions.Handlers.QueryableProjectionScalarHandler.TryHandleLeave(QueryableProjectionContext context, ISelection selection, ISelectionVisitorAction& action)
   at HotChocolate.Data.Projections.ProjectionVisitor`1.Leave(ISelection selection, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(ISelection selection, TContext context)
   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(ISelection selection, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.VisitObjectType(IOutputField field, ObjectType objectType, SelectionSetNode selectionSet, TContext context)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionVisitor.VisitObjectType(IOutputField field, ObjectType objectType, SelectionSetNode selectionSet, QueryableProjectionContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.VisitChildren(IOutputField field, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(IOutputField field, TContext context)
   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(IOutputField field, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.VisitChildren(ISelection selection, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(ISelection selection, TContext context)
   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(ISelection selection, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.VisitObjectType(IOutputField field, ObjectType objectType, SelectionSetNode selectionSet, TContext context)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionVisitor.VisitObjectType(IOutputField field, ObjectType objectType, SelectionSetNode selectionSet, QueryableProjectionContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.VisitChildren(IOutputField field, TContext context)
   at HotChocolate.Data.Projections.SelectionVisitor`1.Visit(IOutputField field, TContext context)
   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(IOutputField field, TContext context)
   at HotChocolate.Data.Projections.ProjectionVisitor`1.Visit(TContext context)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__5`1.<CreateApplicatorAsync>b__5_0(IResolverContext context, Object input)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__DisplayClass4_0`1.<<CreateExecutor>g__ExecuteAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Types.Pagination.PagingMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Additional Context?

After some investigation I found out the Problem is in the ProjectionVisitor. It is trying to assign a `User` object to the User Property of the `Item` which is a string.

### Product

Hot Chocolate

### Version

12.7.0 and also 13.0.0-preview.19

**Comment by rkotenko** [comment]
I am trying to use this exact scenario and have encountered the same issue. I would like to see a fix as well.

**Comment by rkotenko** [comment]
Is there any plan to deal with this?  It becoming a big issue for us as we need to rename many model fields.

**Comment by brianbarenbaum** [comment]
Bump.  Any update on this?  Thanks!

**Comment by melvin78** [comment]
> With 14 we are introducing a new projection engine that is ef core exclusive at the beginning. We will need some time and user feedback. The engine allows for layered architectures to use projections. It has this one fixed and also has a concept for data requirements. I am closing this issue as it is fixed when you use the new engine in 14.

Hi, i think this issue is still recurring in v14 am using `14.0.0-p.122`. Could it be am missing a concept on data requirements.

here is the full stack trace.

`System.ArgumentException: Property 'System.String Description' is not defined for type 'Domain.MainBoundedContext.AdministrationModule.Aggregates.BranchAgg.Branch' (Parameter 'property')
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at HotChocolate.Execution.Projections.SelectionExpressionBuilder.BuildExpression(PropertyNode node, Context context)
   at HotChocolate.Execution.Projections.SelectionExpressionBuilder.BuildExpression(IReadOnlyList`1 properties, Context context)
   at HotChocolate.Execution.Projections.SelectionExpressionBuilder.BuildExpression(PropertyNode node, Context context)
   at HotChocolate.Execution.Projections.SelectionExpressionBuilder.BuildSelectionSetExpression(Context context, PropertyNodeContainer parent)
   at HotChocolate.Execution.Projections.SelectionExpressionBuilder.BuildExpression[TRoot](ISelection selection)
   at GreenDonut.Projections.HotChocolateExecutionDataLoaderExtensions.<>c__5`2.<GetOrCreateExpression>b__5_0(String _, ValueTuple`2 ctx)
   at HotChocolate.Execution.Processing.Operation.GetOrAddState[TState,TContext](String key, Func`3 createState, TContext context)
   at GreenDonut.Projections.HotChocolateExecutionDataLoaderExtensions.GetOrCreateExpression[TKey,TValue](ISelection selection)
   at GreenDonut.Projections.HotChocolateExecutionDataLoaderExtensions.Select[TKey,TValue](IDataLoader`2 dataLoader, ISelection selection)
   at Domain.MainBoundedContext.GraphQLPhoenixEntities.Services.CustomerQueryService.GetCustomerById(Guid id, ISelection selection, CancellationToken cancellationToken)`
