### ISSUE TITLE
IStructuralEquatable on a non collection type causes schema generation to fail

### ISSUE THREAD

**Issue by JacksonCribb** [ChilliCream/graphql-platform#5132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Inheriting System.Collections.IStructuralEquatable outside of a collection causes schema generation to fail.

Expected result would be the schema generated with the offending equality method ignored.

A rarer case in C# but F# records all implement this interface, see #2143 as a less specific duplicate. Adding the ReferenceEquality, or NoComparison + NoEquality attribute to a record results in the interface being omitted from the compiled code, hence the attributes being a workaround. Resolving this should indirectly add support for F# records (and ease further support).  

### Steps to reproduce

Simplest reproduction (anywhere in the schema)
```
public class Example : IStructuralEquatable
{
    public bool Equals(object? other, IEqualityComparer comparer) => throw new NotImplementedException();

    public int GetHashCode(IEqualityComparer comparer) => throw new NotImplementedException();
}
```
Alternate, using F#'s option type
```
using Microsoft.FSharp.Core;
public class Example
{
    public FSharpOption<int> Foo { get; set; }
}
```
F# example
```
type Example = {Foo: string}
// basically equivalent to 
public sealed class Example : IEquatable<Example>, IStructuralEquatable, IComparable<Example>, IComparable, IStructuralComparable { ... }
```

### Relevant log output

```shell
An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.
      
      1. Unable to infer or resolve a schema type from the type reference `Input: IEqualityComparer`.
      
         at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12.10.0, 13.0.0-preview.24

**Comment by michaelstaib** [comment]
I think this should not be the problem. The thing here is that the interface somehow was inferred. We actually only do that if we find a type exposing this interface on a prop

**Comment by michaelstaib** [comment]
Can you create a small repro?

**Comment by michaelstaib** [comment]
I am also open for creating an F# unit test project so that we can better cater to the F# community.

**Comment by JacksonCribb** [comment]
[Here you go.](https://github.com/JacksonCribb/hotcholate-IStructualEquatable-repro)

I'll take a look at the tasks outlined in #3670 and see if there's anything I can contribute to.

**Comment by JacksonCribb** [comment]
Cleaning some things up and Tested again and it's been resolved along the lines.
