### ISSUE TITLE
HotChocolate attempts to register return Types on fields ignored or rebound via type extension

### ISSUE THREAD

**Issue by JEMcAdam** [ChilliCream/graphql-platform#5479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Issue Description**
In the sample project attached there are two separate Dimension types, one is used by a Scenario type(Domain namespace) and the other by a Model Type(Shared namespace).

I want to keep the Domain.Dimension type hidden from the GraphQL schema so have added a TypeExtension class for Scenario which attempts to replace the Scenario.Dimensions member with a new resolver returning an enumerable of a new ScenarioDimension type.

When attempting to query the GraphQL server a SchemaException("The name `Dimension` was already registered by another type. (HotChocolate.Types.ObjectType<HotChocolateBugSample.API.Domain.Types.Dimension>)") is thrown.

**What I would expect**
As the original Dimensions field has now been replaced with the new resolver, I would have expected the schema builder to ignore the Domain.Dimension type, ending with the schema containing only the Shared.Dimension type from Model and the ScenarioDimension type, but it looks to register both types regardless.

I have also attempted to Ignore the type via the BindMember attribute on the TypeExtension class. Is there a way to Ignore the type on the schema, or at least rename it to resolve the type conflict?

### Steps to reproduce

1. Download the attached sample project and launch it.
2. A SchemaException is immediately thrown as introspection begins.

### Relevant log output

```shell
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The name `Dimension` was already registered by another type. (HotChocolate.Types.ObjectType<HotChocolateBugSample.API.Domain.Types.Dimension>)

         at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Additional Context?

[HotChocolateBugSample.zip](https://github.com/ChilliCream/hotchocolate/files/9764816/HotChocolateBugSample.zip)

### Product

Hot Chocolate

### Version

12.15.0

**Comment by michaelstaib** [comment]
Thanks for reporting. This bug is known.  Its an issue in the type initialization. In your case you can work around it with a fluent type. I will fix this one but it might still be 2 or 3 month out before a fix will arrive.

Something like this will work in your case.

```csharp
public class ScenarioType : ObjectType<Scenario>
{
    protected override void Configure(IObjectTypeDescriptor<Scenario> descriptor)
    {
        descriptor.Field(t => t.Dimensions).ResolveWith...
    }
}
```

**Comment by michaelstaib** [comment]
This is now solved with the new `ObjectTypeAttribute` which introduces a new way for type extension in Hot Chocolate 14.
