### ISSUE TITLE
Unable to use error factories to map one exception to another -- schema generation fails

### ISSUE THREAD

**Issue by craigbehnke** [ChilliCream/graphql-platform#5524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What I did
I created an [error factory](https://chillicream.com/docs/hotchocolate/v12/defining-a-schema/mutations/#errors:~:text=C%23-,public%20static%20class%20CreateUserErrorFactory,%7D,-public%20class%20Mutation) to map one exception to another, with the end goal of only having one exception thrown by the mutation in the schema. (Originally I had multiple exceptions mapped, but I removed them in an unsuccessful attempt to troubleshoot the bug.)

### What I expected
There would only be one exception in the schema, avoiding union/fragment complications.

### What happened
The schema now fails to generate.

### Steps to reproduce

1. I created a new catch-all exception class
```
    /// <summary>
    /// The mutation encountered an exception
    /// </summary>
    public class MutationError : Exception
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public MutationError() : base("An unknown exception was encountered.") { }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="message">The exception message</param>
        public MutationError(string message) : base(message) { }
    }
```

2. I created a new error factory
```
    /// <summary>
    /// Factory that converts all exception types into one exception for export
    /// </summary>
    public static class MutationErrorFactory
    {
        /// <summary>
        /// Convert a different, specific exception to a standard, common error
        /// </summary>
        public static MutationError CreateErrorFrom(NotFoundException e)
        {
            return new MutationError(e.Message);
        }
    }
```

3. I then attached this factory to a mutation method so that it would handle the thrown exceptions.

```
    [Error(typeof(MutationErrorFactory))]
    public async Task<List<MyDocument>?> RemoveDocument(string id, [WorkspaceId] string workspaceId)
    {
        // ...actual code removed for brevity
        throw new NotFoundException(); 
    }
```

4. Finally, I ran an integration test, which failed with the log output below.

### Relevant log output

```shell
Assert.IsTrue failed. Request failed with status code InternalServerError.

HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to infer or resolve a schema type from the type reference `Output: DictionaryEntry`.

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 171
   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 246
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Content-Type: application/json; charset=utf-8
Content-Length: 310
Accept: application/json
Authorization: Bearer [[redacted]]
Host: localhost
MyHeader1: [[redacted]]
MyHeader2: [[redacted]]
```

### Additional Context?

- When I remove the `[Error(typeof(MutationErrorFactory))]` attribute from the mutation, the test completes successfully.
- The attribute can be applied to a different mutation that is not used by the test; the test will still fail with the above output.
- Adding a handler for a specific exception (e.g. `[Error(typeof(NotFoundException))]`) works as expected.

### Product

Hot Chocolate

### Version

12.15.1

**Comment by tobias-tengler** [comment]
Your `MutationError` shouldn't inherit from Exception. If it does, Hot Chocolate will try to map all the properties of the Exception class to the schema. Your MutationError just needs to satisfy the Error interface contract by having a `string Message` property. You should treat this "error class" as a type system member.

```csharp
public class MutationError
{
  
   public MutationError() : this("An unknown exception was encountered.") { }

   public MutationError(string message)
   {
        Message = message;
    }

    public string Message { get; }
}
```

**Comment by michaelstaib** [comment]
@tobias-tengler is correct. However, I will create a nicer error for this that tells you exactly that.
