### ISSUE TITLE
Support .NET Hot Reload

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/graphql-platform#5638]
### Is your feature request related to a problem?

It would be nice if the Hot Reload functionality of .NET played nicely with Hot Chocolate:

- Removed and added schema members should be correctly updated (can use the existing schema eviction (replacement) mechanism)
- Changes to Resolver signatures should be correctly handled

### The solution you'd like

A Hot Reload can be intercepted using the [MetadataUpdateHandlerAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadata.metadataupdatehandlerattribute).

I initially explored this in #5165.

### Product

Hot Chocolate

**Comment by glen-84** [comment]
#5165 was merged, not sure if there's more to do?

**Comment by glen-84** [comment]
I get this after a while, so I think I'm going to switch back to `--no-hot-reload` for now.

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Operation is not valid due to the current state of the object. (HotChocolate.Types.StaticObjectTypeExtension)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

**Comment by tobias-tengler** [comment]
@glen-84 Can you open a new bug for it please?

**Comment by glen-84** [comment]
@tobias-tengler I can't really create a reproduction, is it still useful to have an issue?

**Comment by tobias-tengler** [comment]
Yes, it's mainly about organization. It's a new bug that should be tracked separately. And you provided a stack trace at least - that's something to go off of :)
