### ISSUE TITLE
Ignore read-only properties in a binding type of InputObjectType from inferred fields

### ISSUE THREAD

**Issue by sunghwan2789** [ChilliCream/graphql-platform#5673]
### Product

Hot Chocolate

### Is your feature request related to a problem?

It would be great if I can reuse a binding type for both `ObjectType` and `InputObjectType`, without configuring.

Given application fails to startup:

```cs
using HotChocolate.Execution;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddGraphQLServer()
    .AddQueryType(type => type.Field("foo").Resolve(() => "bar"))
    .AddMutationType<Mutation>()
    .InitializeOnStartup()
    ;

var app = builder.Build();

var executor = await app.Services.GetRequestExecutorAsync();
Console.WriteLine(executor.Schema);

public class Mutation {
    public Metadata PutMetadata(Metadata input) => input;
}

public class Metadata {
    public Metadata(int id) {
        Id = id;
    }

    public int Id { get; }
    public int Hash => Id;
}
```

with an exception that it cannot set value to `Metadata.Hash`:
```
Unhandled exception. System.InvalidOperationException: No compatible constructor found for input type type `Metadata`.
Either you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties. There was no way to set the following properties: .
   at HotChocolate.Utilities.Serialization.InputObjectConstructorResolver.GetCompatibleConstructor[T](Type type, FieldCollection`1 fields, IReadOnlyDictionary`2 fieldMap)
   at HotChocolate.Utilities.Serialization.InputObjectCompiler.CompileFactory(InputObjectType inputType, ConstructorInfo constructor)
   at HotChocolate.Types.InputObjectType.OnCompleteCreateInstance(ITypeCompletionContext context, InputObjectTypeDefinition definition)
   at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__29_0(RegisteredType type)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /Users/sunghwan2789/Desktop/csharp/Program.cs:line 13
   at Program.<Main>(String[] args)
```

I think it is normal when fields are bound explicitly, but implicit binding could ignore some read-only properties.

### The solution you'd like

Human-generated read-only properties are ignored from inferred fields of `InputObjectType`.

For example, 
* `typeof(Metadata).GetProperty(nameof(Metadata.Id)).GetMethod.GetCustomAttribute<CompilerGeneratedAttribute>()` is not null, so it is included.
* `typeof(Metadata).GetProperty(nameof(Metadata.Hash)).GetMethod.GetCustomAttribute<CompilerGeneratedAttribute>()` is null, so it is ignored.

Expecting generated schema:

```gql
type Mutation {
  putMetadata(input: MetadataInput!): Metadata!
}

input MetadataInput {
  id: Int!
}

type Metadata {
  id: Int!
  hash: Int!
}
```

Related code, maybe?

https://github.com/ChilliCream/hotchocolate/blob/af14b1ff0e1e2dfea9deb0912b274f7dc57aacd7/src/HotChocolate/Core/src/Types/Types/Descriptors/InputObjectTypeDescriptor.cs#L100

**Comment by atykhyy** [comment]
A related problem is that record types using the C# 9 `get; init;` pattern for properties also cause schema initialization to fail with 'No compatible constructor' when they are used as input types.

**Comment by atykhyy** [comment]
It would certainly be useful to detect and ignore such computed properties, but it's not trivial. E.g. how about this perfectly valid code?

```
public class Metadata {
    private readonly int m_id;
    public Metadata(int id) {
        m_id = id;
    }

    public int Id => m_id;
    public int Hash => Id;
}
```
