### ISSUE TITLE
Unable to resolve type reference `DateTimeOffset!` Schema Stitching 

### ISSUE THREAD

**Issue by jedyskate** [ChilliCream/graphql-platform#5686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

There is an issue with hotchocolate Schema Stitching and scalar type DateTimeOffset.

**This is my remote schema is using scalar DateTimeOffset!:**
![image](https://user-images.githubusercontent.com/18351422/212473211-e3d10df7-db1a-4c90-8346-753fb0acb7b0.png)

![image](https://user-images.githubusercontent.com/18351422/212473581-394554e8-4ff1-4a48-a3c4-bc0e448d1019.png)

**HotChocolate is complaining about it the scalar type**

**I have tried this but it doesn't work:**
`
                .BindRuntimeType<OffsetDateTime, DateTimeType>()
                .AddTypeConverter<OffsetDateTime, DateTimeOffset>(
                    x => x.ToDateTimeOffset())
                .AddTypeConverter<DateTimeOffset, OffsetDateTime>(
                    x => OffsetDateTime.FromDateTimeOffset(x))
`

I would appreciate if someone can guide me how to solve this issue. I tried pulled this repo but I'm not sure I can fix it myself. Thank you.

JC

### Steps to reproduce

1. Create a Remote schema with a query that returns a DateTimeOffsetGraphType 
![image](https://user-images.githubusercontent.com/18351422/212474724-a7199b95-eca9-4698-925a-877d46e7ef0f.png)

2. Create a hotchocolate graphql API and use remote schema.
 

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `None: DateTimeOffset!`. (HotChocolate.Types.ObjectType)

   at HotChocolate.Configuration.RegisteredType.GetType[T](ITypeReference typeRef)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
   at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
   at HotChocolate.Types.ObjectType.OnCompleteFields(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|27_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 46
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 46
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: localhost:5001
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
:method: POST
Accept-Encoding: gzip, deflate, br
Accept-Language: en-AU,en;q=0.9
Cache-Control: no-cache
Content-Type: application/json
Origin: https://localhost:5001
Pragma: no-cache
Referer: https://localhost:5001/graphql/static/js/document.ece7e0e9.chunk.js
Content-Length: 12
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
```

### Additional Context?

My remote schema was built using graphql-dotnet and it uses the following:

    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.0.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="6.0.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="4.8.0" />

### Version

12.16.0

**Comment by robotgryphon** [comment]
I have a near-identical issue with both HC12 and HC13, using the `Types.Scalars` package provided by the platform. I've created a super small repro case here to demonstrate: https://github.com/robotgryphon/hotchocolate-stitching-scalars

Steps:

1. Create a server that uses a custom scalar (in this case, `UnsignedInt`)
2. Create a stitching server that pulls in the schema for the other server.
3. Attempt to use the stitched schema. The stitching server fails to start.

**Comment by benmccallum** [comment]
With custom scalars, unfortunately they don't "auto-add" to the stitched schema even though they are already declared downstream. You need to add them also onto the gateway schema. 

e.g.
```c# 
var gatewayBuilder = services
    .AddGraphQLServer()
    .AddRemoteSchema("A")
    .AddRemoteSchema("B")
    .AddType<MyCustomScalar>()
```

This might be better once the new stitching engine (Fusion) comes along.
