### ISSUE TITLE
Unable to use Guid property in Apollo Federation reference resolver

### ISSUE THREAD

**Issue by willwolfram18** [ChilliCream/graphql-platform#5843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When creating a `[ReferenceResolver]` using the Apollo Federation package, a user cannot use a `Guid` property and/or parameter in the reference resolver. When you try to do this, the Hot Chocolate engine produces an `InvalidCastException` instead of trying to check if the string can be parsed as a Guid.

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Guid'.
         at HotChocolate.ApolloFederation.Helpers.ArgumentParser.TryGetValue[T](IValueNode valueNode, IType type, String[] path, Int32 i, T& value)
         at HotChocolate.ApolloFederation.Helpers.ArgumentParser.TryGetValue[T](IValueNode valueNode, IType type, String[] path, Int32 i, T& value)
         at lambda_method28(Closure, IResolverContext)
         at HotChocolate.ApolloFederation.Helpers.EntitiesResolver.ResolveAsync(ISchema schema, IReadOnlyList`1 representations, IResolverContext context)
         at HotChocolate.Types.ResolveObjectFieldDescriptorExtensions.<>c__DisplayClass3_0`1.<<Resolve>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Workaround
You can change the argument's type to a `string` and perform the `Guid.Parse()` and/or `Guid.TryParse()` within your method directly.

### Steps to reproduce

1. Add the `HotChocolate.ApolloFederation` and `HotChocolate.AspNetCore` packages to the project
1. Create an Apollo Federation entity that has the following:
    * A property annotated with the `[Key]` attribute that is of type `Guid`
    * A `public static` method that is annotated with the `[ReferenceResolver]` attribute, and takes an argument of type `Guid`
1. Register the Hot Chocolate libraries, the entity type, and an empty Query type in the API
```csharp
services.AddGraphQLServer()
    .AddApolloFederation()
    .AddType<YourEntityType>()
    .AddQueryType();
```
4. Submit a query to resolve the entity
```gql
query {
  _entities(representations: [ { id: "<guid value>", __typename: "YourEntityType" } ]) {
    ... on YourEntityType { id }
  }
}
```
5. View the API's response; it should be something like the following
```json
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "_entities"
      ]
    }
  ]
}
```

I've created an example API that provides a more thorough example of how to reproduce this issue as well: https://github.com/willwolfram18/hot-chocolate-guid-reference-resolver

### Additional Context?

I've listed two different versions below because I'm using the 12.13 version for projects at work, and I was able to reproduce the issue in my sample above with the latest 13.0.2 version.

### Version

12.13.0+, 13.0.2

**Comment by michaelstaib** [comment]
This one is fixed with 14
