### ISSUE TITLE
DefaultBindingBehavior doesn't work anymore in BindingBehavior.Explicit mode.

### ISSUE THREAD

**Issue by DkozhevnikovConfigit** [ChilliCream/graphql-platform#5850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I'm currently working on HotChocolate 12 to 13 migration.
I'm getting exception during the schema initialization:

```
System.ArgumentException: Type HotChocolate.Types.ObjectType`1[T] contains generic parameters (Parameter 'constructor')
```
I remember I had the same issue before with HC 12, the solution then was to set the flag(SchemaOptions.DefaultBindingBehavior = BindingBehavior.Explicit;) in schema options, but looks like it's not the case anymore.
The thing is I have some classes within my GraphQL model where methods or properties returning T or T[], the worst thing I can't change them, because they are from a third party library.

[WebApplicationExlicitDefaultBindingProblem.zip](https://github.com/ChilliCream/graphql-platform/files/10756892/WebApplicationExlicitDefaultBindingProblem.zip)

### Steps to reproduce

1. Open attached solution.
2. Run it.

### Relevant log output

```shell
System.ArgumentException: Type HotChocolate.Types.ObjectType`1[T] contains generic parameters (Parameter 'constructor')
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Int32 index)
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Boolean allowByRef, Boolean allowPointer)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at HotChocolate.Utilities.ActivatorHelper.CreateNewInstance(Type type, ParameterExpression services)
   at HotChocolate.Utilities.ActivatorHelper.<>c__DisplayClass4_0.<CompileFactory>b__0(Type _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at HotChocolate.Utilities.ActivatorHelper.CompileFactory(Type type)
   at HotChocolate.Utilities.ServiceFactory.CreateInstance(Type type)
```

### Version

13.0.2

**Comment by Socolin** [comment]
Hello, I have the same problem

**Comment by jarlef** [comment]
Hi. I had the same problem during the RC builds and reported this issue https://github.com/ChilliCream/graphql-platform/issues/5709. Michael made a fix, but i never got around to verifying it. Its still an issue for the current version 13.0.5. 

When setting `DefaultBindingBehavior` to `Explicit` on the RequestExecutionBuilder the  schema `Options` property on `DescriptorContext` still says `Implicit` on all ObjectTypeDescriptors

```csharp
.ModifyOptions(options =>
    {
        options.DefaultBindingBehavior = BindingBehavior.Explicit;
    });
```

```csharp
   // debugging the descriptorcontext using TypeInterceptor
    public override void OnBeforeInitialize(ITypeDiscoveryContext discoveryContext)
    {
        // still says implicit
        Console.WriteLine(discoveryContext.DescriptorContext.Options.DefaultBindingBehavior);
    }
```

I think this is due to the options being lost in the `CreateSchemaAsync` method on the `RequestExecutionResolver.cs`

```csharp
...
// the schemabuilder is recreated and never picked up from options.SchemaBuilder.
// the new schema builder contains a clean options where the DefaultBindingBehavior is Implicit
var schemaBuilder = options.SchemaBuilder ?? new SchemaBuilder();
...
 ```

The only workaround on is this dodgy hack using a TypeInterceptor

```csharp

public class BindingTypeInterceptor : TypeInterceptor
{
    public override void OnBeforeCreateSchema(IDescriptorContext context, ISchemaBuilder schemaBuilder)
    {
        // there is a bug in HC version 13 where the default binding configuration is lost during creation of the schema.
        // this hack pops the readonly options on the context over to schema options and resets the binding options
        var options = Unsafe.As<SchemaOptions>(context.Options);
        options.DefaultBindingBehavior = BindingBehavior.Explicit;
        options.DefaultFieldBindingFlags = FieldBindingFlags.Default;
        base.OnBeforeCreateSchema(context, schemaBuilder);
    }
}

```

**Comment by michaelstaib** [comment]
This is now fixed and will be included into 13.2.0-rc.1

**Comment by jarlef** [comment]
Great work 👍
