### ISSUE TITLE
Unable to resolve type reference `LocalDateTime` in Gateway(Schema Stitching)

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/graphql-platform#5882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I've added a custom scalar (LocalDateTime) to one of my micro services. when I added this micro to gateway,getting an error like "Unable to resolve type reference `LocalDateTime`. (HotChocolate.Types.ObjectType)".

Previously, I got an error in HC Version 12.5.0, based on the workaround given [here](https://github.com/ChilliCream/graphql-platform/issues/4682), it get resolved.

and later it get fixed in 13.0.0-preview.24 version, i.e without adding workaround solution.it worked, but now in latest stable release of 13.0.4, we are getting the same error and the workaround provided for Version 12.5 also not works.

### Steps to reproduce

1. use custom scalar to one of 2 microservice schemas and then fed the microschema to gateway

### Relevant log output

```shell
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5003
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: F:\Codegen\Dotnet\fed-13-update\com.ramco.gql.Federation
info: System.Net.Http.HttpClient.CPOAPI.LogicalHandler[100]
      Start processing HTTP request POST http://localhost:5005/CPOAPI
info: System.Net.Http.HttpClient.CPOAPI.ClientHandler[100]
      Sending HTTP request POST http://localhost:5005/CPOAPI
info: System.Net.Http.HttpClient.CPOAPI.ClientHandler[101]
      Received HTTP response headers after 218.1635ms - 200
info: System.Net.Http.HttpClient.CPOAPI.LogicalHandler[101]
      End processing HTTP request after 279.1194ms - 200
info: System.Net.Http.HttpClient.CPOAPI.LogicalHandler[100]
      Start processing HTTP request POST http://localhost:5005/CPOAPI
info: System.Net.Http.HttpClient.CPOAPI.ClientHandler[100]
      Sending HTTP request POST http://localhost:5005/CPOAPI
info: System.Net.Http.HttpClient.CPOAPI.ClientHandler[101]
      Received HTTP response headers after 119.1615ms - 200
info: System.Net.Http.HttpClient.CPOAPI.LogicalHandler[101]
      End processing HTTP request after 139.4065ms - 200
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to resolve type reference `LocalDateTime`. (HotChocolate.Types.ObjectType)

         at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
         at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
         at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
         at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
         at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
         at HotChocolate.Types.ObjectType.OnCompleteFields(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: System.Net.Http.HttpClient.CPOAPI.LogicalHandler[100]
```

### Version

13.0.4

**Comment by Coltonls24** [comment]
I am having a similar issue with the `HotChocolate.Types UnsignedLongType`. We have it added to both the downstream api as well as the gateway. On the gateway we get the following error
![image](https://user-images.githubusercontent.com/27246171/220737791-affd359e-f55c-4cd9-b363-8656f68a863c.png)

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.

You can join the preview of Hot Chocolate Fusion now on Slack
