### ISSUE TITLE
Banana Cake Pop

### ISSUE THREAD

**Issue by jackdh** [ChilliCream/graphql-platform#6021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

It looks like when CSS is injected into the page it causes BCP to break with the error:

`Error: Illegal value for token color:  #cbd0db`

This is not a big issue as you can just turn off the addon, however thought it might still be worth mentioning.

### Steps to reproduce

1. Install Dark Reader addon
2. https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en
3. Attempt to load Banana Cake Pop

### Relevant log output

```shell
"Error: Illegal value for token color:  #cbd0db\n    at h.getId (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2517080)\n    at http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2518389\n    at u.createFromParsedTokenTheme (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2518574)\n    at u.createFromRawTokenTheme (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2517443)\n    at get tokenTheme [as tokenTheme] (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2529432)\n    at B._updateThemeOrColorMap (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2533823)\n    at B._updateActualTheme (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2533054)\n    at B.setTheme (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:2532970)\n    at new qa (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:3437114)\n    at da._createInstance (http://localhost:60899/api/graphql/static/js/297.2b369f7b.chunk.js:2:3411301)"
```

### Version

13.0.5

**Comment by rstaib** [comment]
@jackdh please test with the insider version: https://insider.bananacakepop.com/

Also with the upcoming bcp v5 we're introducing new themes 👍🏻

**Comment by artola** [comment]
@jackdh The error is produced by the extension, because the color contains some whitespace and there is a regexp check that is not passing.
Same for former version as any new.
From Slack thread:

It seems that such extension does not properly change the colors as expected, something in the range #000000  to #ffffff  that it is verified with a regex.
The extension tries to modify the color as " #24292f"  (see space before the hash).
I will check if it is possible to change such regexp in our side and ignore the whitespace, otherwise the extension should be fixed in their end.
The code that throws is “monaco”.

**Comment by artola** [comment]
@jackdh @rstaib The bug is produced by the extension, but we can avoid it in our side with a small fix to remove the whitespace that breaks "monaco" regex for colors.
Preparing PR to get into `insider.bananacakepop.com` today, and asap into v5 release.
