### ISSUE TITLE
`JSON` scalar crashes on JsonElement inputs

### ISSUE THREAD

**Issue by onionhammer** [ChilliCream/graphql-platform#6023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When an input is of type `JSON`, HotChocolate crashes for numeric inputs (such as `10`), with the following exception

```
System.Text.Json.JsonReaderException: '0x00' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 6.
```

### Steps to reproduce

1. Create an input with a property of type `JsonElement` in HC13
```C#
[QueryType]
public static class JsonBasedQuery
{
    public static string GetDataWithFilter(FilterType input)
    {
        return "hello";
    }

    public class FilterType
    {
        public string? Name { get; set; }
        public System.Text.Json.JsonElement Value { get; set; }
    }
}
```

2. Invoke it with a number literal
```graphql
query {
  dataWithFilter(input: {
    name: "hello"
    value: 10
  })
}
```

### Relevant log output

      GraphQL service exception for 'POST /graphql/UnknownOperation - 4a22f1afa6b4662d460ab8929d3c10f6': '0x00' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 2.
      System.Text.Json.JsonReaderException: '0x00' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 2.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)        
         at System.Text.Json.Utf8JsonReader.TryGetNumber(ReadOnlySpan`1 data, Int32& consumed)
         at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.JsonDocument.TryParseValue(Utf8JsonReader& reader, JsonDocument& document, Boolean shouldThrow, Boolean useArrayPools)
         at System.Text.Json.JsonElement.ParseValue(Utf8JsonReader& reader)
         at HotChocolate.Types.JsonType.JsonFormatter.Format(IValueNode node)
         at HotChocolate.Types.JsonType.ParseLiteral(IValueNode valueSyntax)
         at HotChocolate.Types.InputParser.ParseLeaf(IValueNode resultValue, ILeafType type, Path path, IInputFieldInfo field)
         at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputFieldInfo field)  
         at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputFieldInfo field)  
         at HotChocolate.Types.InputParser.ParseObject(IValueNode resultValue, InputObjectType type, Path path, Int32 stack, Boolean defaults)
         at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputFieldInfo field)  
         at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputFieldInfo field)  
         at HotChocolate.Types.InputParser.ParseLiteral(IValueNode value, IInputFieldInfo field, Type targetType)
         at HotChocolate.Execution.Processing.MiddlewareContext.CoerceArgumentValue[T](ArgumentValue argument)
         at HotChocolate.Execution.Processing.MiddlewareContext.ArgumentValue[T](String name)
         at DataAnnotatedModelValidations.ValidatorMiddleware.<>c__DisplayClass6_0.<ReportErrorFactory>b__0(IInputField argument)
         at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
         at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
         at System.Linq.Parallel.SpoolingTaskBase.Work()
         at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

### Version

13.0.5

**Comment by onionhammer** [comment]
Seems like this code
![image](https://user-images.githubusercontent.com/969938/230200541-40a8babc-eef5-46e1-82c6-ff154817ca2a.png)

Seems like the visitor is not flushing the bytes to the underlying bufferWriter before attempting to parse it
