### ISSUE TITLE
impossible to fetch schema

### ISSUE THREAD

**Issue by davidegolzi** [ChilliCream/graphql-platform#6037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

when i try to fetch schema from https://api.travelgatex.com nothing heppend

also from  dotnet graphql init https://api.travelgatex.com
i get back a timout error.

I know that it works because with other software like Insomnia or Postman the schema is fetched and i was able to make query and mutation

I manually extract the schema so i can go on and build my application, but should be better to meke it works just in case of update.

### Steps to reproduce

1. Add new document in Banana cake pop

or

2. execute "dotnet graphql init https://api.travelgatex.com" command

### Relevant log output

```shell
From command Execution:

dotnet graphql init https://api.travelgatex.com
Download schema started.
Download schema completed in 100051 ms
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operazione di I/O terminata a causa dell'uscita dal thread oppure della richiesta di un'applicazione..
 ---> System.Net.Sockets.SocketException (995): Operazione di I/O terminata a causa dell'uscita dal thread oppure della richiesta di un'applicazione.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at HotChocolate.Utilities.Introspection.IntrospectionClient.ExecuteIntrospectionAsync(HttpClient client, HttpQueryRequest request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 135
   at HotChocolate.Utilities.Introspection.IntrospectionClient.GetSchemaFeaturesAsync(HttpClient client, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 92
   at HotChocolate.Utilities.Introspection.IntrospectionClient.DownloadSchemaAsync(HttpClient client, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 67
   at HotChocolate.Utilities.Introspection.IntrospectionClient.DownloadSchemaAsync(HttpClient client, Stream stream, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 49
   at StrawberryShake.Tools.DefaultFileSystem.WriteToAsync(String fileName, Func`2 write) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/DefaultFileSystem.cs:line 81
   at StrawberryShake.Tools.IntrospectionHelper.DownloadSchemaAsync(HttpClient client, IFileSystem fileSystem, IActivity activity, String fileName, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/IntrospectionHelper.cs:line 21
   at StrawberryShake.Tools.InitCommandHandler.DownloadSchemaAsync(InitCommandContext context, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/InitCommandHandler.cs:line 110
   at StrawberryShake.Tools.InitCommandHandler.ExecuteInternalAsync(InitCommandContext context, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/InitCommandHandler.cs:line 87
   at StrawberryShake.Tools.InitCommandHandler.ExecuteAsync(InitCommandArguments arguments, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/InitCommandHandler.cs:line 73
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at StrawberryShake.Tools.Program.<Main>(String[] args)
```

### Additional Context?

i'm using latest version(4.0.1) of Banana Cake pop

and 
version: 13.0.5 of strawberryshake.tools

### Version

4.0.1

**Comment by michaelstaib** [comment]
Its a server issue ... I tried an introspection query and it failed also with their own playground:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/9714350/231277187-c880e588-9896-47b2-b400-32e9a90d3615.png">

**Comment by michaelstaib** [comment]
You can ask them for a GraphQL SDL and use that instead.

**Comment by michaelstaib** [comment]
But that's a server issue, as the server must execute just any introspection query I provide or throw an error. I tested with postman same issue.

**Comment by davidegolzi** [comment]
Sorry @michaelstaib  but this is a screenshoot by postman:
![image](https://user-images.githubusercontent.com/76689954/231516824-2e7d98b3-05a3-4041-80b9-3eeb2359565b.png)
as soon i inetered the url postman retrive the schema and show it

**Comment by michaelstaib** [comment]
Try to run the standard introspection query as pointed out in the graphql spec appendix.

**Comment by michaelstaib** [comment]
Here... postman died ... and is stuck forever... it cancels out after a minute or so.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/9714350/231517910-15dc204d-10f0-455a-b3c9-d386da621c8e.png">

**Comment by davidegolzi** [comment]
> Try to run the standard introspection query as pointed out in the graphql spec appendix.

Ok so maybe is a problem related to an incompatibility with the spec, but i think that for your product is a limitation due the fact that your competitors (Banana Cake Pop product) are able to consume this type of service.
So i can accept a we son't want to implement any compatibility for this kind of service.

Anyway i'l go to check the specs

**Comment by michaelstaib** [comment]
No ... postman is also dead if you fetch the schema. Insomnia is also dead if you fetch the schema through introspection. See the screen.

**Comment by davidegolzi** [comment]
![image](https://user-images.githubusercontent.com/76689954/231520165-c57259e2-0750-4dde-93f2-edbb361ef57e.png)
this is a screenshot of a running query build with postman.

**Comment by davidegolzi** [comment]
to run this query you have to set an api key in the headers, but to retrive the schema postman do not need the api key

**Comment by michaelstaib** [comment]
I see the issue this server has ... the operation name must be introspection query ... could be some kind of approach to failed security. We can name it Introspection Query also its really two ... but this pretty much will break at the next server that does not adhere to that.

**Comment by davidegolzi** [comment]
could be something to put in the client configuration?

**Comment by davidegolzi** [comment]
or a second try after the timoout period expired

**Comment by michaelstaib** [comment]
Not sure yet ... but I am a bit on the fence of this as there is a spec to adhere to. Either run a quert or fail a query... if you limit introspection do it the right way by traversing the query. I will speak with the team if we do something about this, not sure yet.

**Comment by davidegolzi** [comment]
If you don't consider this a bug can you consider like e feture ?

**Comment by michaelstaib** [comment]
cc @rstaib, @artola

**Comment by rstaib** [comment]
we'll rename the introspection query to `IntrospectionQuery`. @artola is right now on it. this will be shipped with BCP V5.
