### ISSUE TITLE
Missing deserialization for fragments in query that has the same field multiple times

### ISSUE THREAD

**Issue by SeijiSuenaga** [ChilliCream/graphql-platform#6130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

This issue is a bit tricky to describe, please bear with me:

When generating client code for a query that requests the same interface-typed field multiple times (with different arguments, type fragments, and field aliases), the client only tries to deserialize the fragment types in whichever field selection is defined *first*.

### Steps to reproduce

For example, given a type with an interface-typed field that takes a parameter:
```graphql
type Example {
  someField(someParameter: String!): ISomeInterface
}
```
When querying the field multiple times with different arguments and fragments:
```graphql
query GetMultiple {
  example {
    someField("foo") {
      ... on FirstInterfaceImplementation { someString }
    }
    someField("bar") {
      ... on SecondInterfaceImplementation { someNumber }
    }
  }
}
```
The generated client will only include deserialization for `FirstInterfaceImplementation` and will return an error like this when trying to deserialize data for `SecondInterfaceImplementation` (this stack trace might not be exactly accurate, I hand-edited it to replace my own identifiers with the example ones):
```c#
StrawberryShake.ClientError
{
        Code = "SS1000",
        Exception = System.ArgumentNullException with message "Value cannot be null."
             at Example.GraphQL.Generated.State.GetMultipleResultFactory.MapIGetMultiple_Example_SomeField(IISomeInterfaceData data)
             at Example.GraphQL.Generated.State.GetMultipleResultFactory.MapIGetMultiple_Example(ExampleData data)
             at Example.GraphQL.Generated.State.GetMultipleResultFactory.Create(IOperationResultDataInfo dataInfo, IEntityStoreSnapshot snapshot)
             at StrawberryShake.OperationResultBuilder`1.Build(Response`1 response)
        ,
        Extensions = {["StackTrace"] = "omitted for brevity"},
        Locations = <null>,
        Message = "Value cannot be null.",
        Path = <null>
}
```
I've found that we can work around this problem by specifying all desired fragment types in the *first* selection of the interface-typed field:
```graphql
query GetMultiple {
  example {
    someField("foo") {
      ... on FirstInterfaceImplementation { someString }
     # This is included here just so it gets included in code generation
     # and can be deserialized in the other field selection below 
      ... on SecondInterfaceImplementation { someNumber }
    }
    someField("bar") {
      ... on SecondInterfaceImplementation { someNumber }
    }
  }
}
```

### Version

13.0.5

**Comment by LJJimChen** [comment]
I have found the same issue on version 13.5.1
