### ISSUE TITLE
Operation Complexity @cost directives can't be added when a Payload has no fields

### ISSUE THREAD

**Issue by tiagooc** [ChilliCream/graphql-platform#6196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Operation Complexity @cost directives can't be added when a Payload has no fields.

I've added a sample project with a MyMutationPayload which has no fields. If I had any field to the payload it starts working again (the first commit in this repo has this scenario).

We should be able to add cost directives even when our schema has Payload objects without any property (for example, in this case, I only want the errors and nothing else so I've created an empty MyMutationPayload class).

### Steps to reproduce

1. Clone the following repo: https://github.com/tiagooc/hotchocolate-playground
2. Look at MyMutationPayload (it has no fields)
3. Run the application
4. Get the following exception:
![image](https://github.com/ChilliCream/graphql-platform/assets/3987453/5cb02129-870b-4228-8991-f8cf2e812a56)

### Relevant log output

```shell
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The specified directive `@cost` is not allowed on the current location `FieldDefinition`. (HotChocolate.Types.ObjectType<Demo.Mutation.MyMutationPayload>)

         at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMoni
tor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Version

13.0.1

**Comment by michaelstaib** [comment]
we have a new cost analyzer as part of Hot Chocolate 14 that covers a lot more use-cases. Check It out.
