### ISSUE TITLE
Remote Schemas with Redis don't recognise scalars

### ISSUE THREAD

**Issue by AlexeyRaga** [ChilliCream/graphql-platform#6240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

There are services that use HotChocolate's `NonEmptyString` scalar (and some others, defined in `HotChocolate.Types.Scalars` package.

I am trying to stitch these services using `Redis` as per [this](https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/Stitching/federated-with-hot-reload) example.

The gateway, when run, is reporting this error:

```
1. Unable to resolve type reference `NonEmptyString`. (HotChocolate.Types.ObjectType)
```

I tried registering the remote schema without Redis, with just `AddRemoteSchema` and got the same error.
I was able to "fix" the error in this case by forcibly registering the scalar type for each remote schema:

```csharp
builder
  .AddRemoteSchema(name)
  .AddGraphQL(name)
  .AddType<NonEmtpyStringType>() // <--- this "fixes" the error
```

However, when remote schemas are coming from Redis, I do not see any way of controlling how they are built and injecting the types.

### Steps to reproduce

1. Create a remote schema that uses `[GraphQLType(typeof(NonEmptyStringType))]` attribute on one of the types
2. Stitch this schema using `AddRemoteSchemasFromRedis` functionality. Most likely the provided [example](https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/Stitching/federated-with-hot-reload) will manifest the same issue when the attribute is used on one of the services that it stitches.

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `NonEmptyString`. (HotChocolate.Types.ObjectType)

   at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Types.FieldBase`1.HotChocolate.Types.Helpers.IFieldCompletion.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
   at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
   at HotChocolate.Types.ObjectType.OnCompleteFields(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__29_0(RegisteredType type)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__9>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Execution.RequestExecutorResolver.OnConfigureSchemaBuilderAsync(ConfigurationContext context, IServiceProvider schemaServices, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Additional Context?

The stitching gateway uses HotChocolate `13.2.0`.
The remote schemas are built with HotChocolate `12.18.0`

### Version

13.2.0

**Comment by AlexeyRaga** [comment]
I have tried to implement this simple decorator to inject `AddType<NonEmptyStringType>()`:

```csharp
public sealed class DecoratedRequestExecutorProvider : IRequestExecutorOptionsProvider
{
    private readonly IRequestExecutorOptionsProvider _inner;

    public DecoratedRequestExecutorProvider(IRequestExecutorOptionsProvider inner)
    {
        _inner = inner ?? throw new ArgumentNullException(nameof(inner));
    }

    public async ValueTask<IEnumerable<IConfigureRequestExecutorSetup>> GetOptionsAsync(CancellationToken cancellationToken)
    {
        var options = await _inner.GetOptionsAsync(cancellationToken).ConfigureAwait(false);
        return options
            .Select(opt =>
            {
                return new ConfigureRequestExecutorSetup(opt.SchemaName, setup =>
                {
                    var act = new OnConfigureSchemaBuilderAction((context, services) =>
                    {
                        context.SchemaBuilder
                            .AddType<NonEmptyStringType>()
                            .AddType<EmailAddressType>()
                            .AddType<UuidType>();
                    });
                    setup.OnConfigureSchemaBuilderHooks.Add(act);
                    opt.Configure(setup);
                });
            })
            .ToList();
    }

    public IDisposable OnChange(Action<IConfigureRequestExecutorSetup> listener) => _inner.OnChange(listener);
}
```

and then use it as:
```csharp
builder
    .AddRemoteSchemasFromRedis("GraphQL", sp => sp.GetRequiredService<ConnectionMultiplexer>())
    .Services
    .Decorate<IRequestExecutorOptionsProvider, DecoratedRequestExecutorProvider>();
```

And the decorator was called, but then I started getting all these errors:

```
1. Unable to find type(s) @authorise, HotChocolate.Types.UuidType (HotChocolate.Types.ObjectType)
2. Unable to resolve dependencies UUID!, @authorise, @delegate, [UUID!]!, @authorise, @delegate, String!, PaginationInput!, [SortFieldInput!], AdminFilterInput, @authorise, @delegate, @delegate, UUID!, @delegate, @authorise, @delegate, UUID!, @authorise, @delegate, UUID!, UUID!, @authorise, @delegate, UUID!, @delegate, UUID!, @delegate, String!, FilterInput!, SortInput!, PaginationInput, @authorise, @delegate, String!, OrganisationType, PaginationInput, @authorise, @delegate for type `Query`. (HotChocolate.Types.ObjectType)
3. Unable to find type(s) @authorise, HotChocolate.Types.UuidType, HotChocolate.Types.StringType (HotChocolate.Types.ObjectType)
4. Unable to resolve dependencies String!, UUID!, @authorise, @delegate, String!, UUID!, @authorise, @delegate, OrganisationProductAccessInput!, @authorise, @delegate, OrganisationProductAccessInput!, @authorise, @delegate, UserProductAccessInput!, @authorise, @delegate, UserProductAccessInput!, @authorise, @delegate, String!, UUID!, String!, UserRole!, [UUID!]!, @authorise, @delegate, String!, UUID!, UUID!, String!, @delegate, UUID!, @authorise, @delegate, RegisterAdminInput!, @authorise, @delegate, UUID!, String!, String!, @authorise, @delegate for type `Mutation`. (HotChocolate.Types.ObjectType)
```

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is replaced by HotChocolate.Fusion. I am closing this issue as HotChocolate.Stitching is eol.

**Comment by AlexeyRaga** [comment]
@michaelstaib Where do I find documentation for `HotChocolate.Fusion` and how to do remote schemas with it?
