### ISSUE TITLE
Could not load type 'HotChocolate.Utilities.TypeConverterServiceProviderExtensions'

### ISSUE THREAD

**Issue by bensmind** [ChilliCream/graphql-platform#6247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Upgraded to 13.2.0 and started recieving the following error when running the snapshot unit test in our project with no other changes.

```C#
1. Could not load type 'HotChocolate.Utilities.TypeConverterServiceProviderExtensions' from assembly 'HotChocolate.Types, Version=13.2.0.0, Culture=neutral, PublicKeyToken=null'.

  Stack Trace:
     at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorServiceProviderExtensions.BuildSchemaAsync(IRequestExecutorBuilder builder, String schemaName, CancellationToken cancellationToken)
   at Schema_Matches_Snapshot() in 
```

The test:
```C#
    public class SchemaTests
    {
        private readonly ITestOutputHelper _outputHelper;

        public SchemaTests(ITestOutputHelper output)
        {
            _outputHelper = output;
        }

        [Fact]
        public async Task Schema_Matches_Snapshot()
        {
            // arrange
            var schema = await new ServiceCollection()
                .AddGraphQLServer()
                .ConfigureHotChocolate() //This is our method that encapsulates all of our HC setup/configuration
                .BuildSchemaAsync();

            try
            {
                // act
                var schemaSdl = schema.ToString();

                // assert
                schemaSdl.MatchSnapshot();
            }
            catch (HotChocolate.SchemaException)
            {
                throw;
            }
        }
    }
```

ConfigrueHotChocolate method
```C#
public static class GraphqlExtensions
{
    internal static class HPHGraphQLExtensions
    {
        public static IRequestExecutorBuilder ConfigureHotChocolate(this IRequestExecutorBuilder b)
        {
            b.RegisterDbContext<CoreDbContext>()
            .AddHttpRequestInterceptor<RequestInterceptor>()
            .AddQueryType<Query>()
            .AddMutationType<Mutation>()
            .AddSubscriptionType<Subscription>()
            .AddGlobalObjectIdentification()
            .AddInMemorySubscriptions()
            .AddFiltering()
            .AddProjections()
            .AddSorting()
            .AddAuthorization()
            .AddType<UploadType>();

            //... 
        }    
    }
}

### Steps to reproduce

1. Using HC 13.0.5
2. Add the above unit test to a test project
3.  Run the test ensure that it succeeds
4. Upgrade to HC 13.2.0
5. Observe the thrown exception

### Relevant log output

_No response_

### Additional Context?

_No response_

### Version

13.2.0

**Comment by michaelstaib** [comment]
We have a technical breaking change in the patch. Do you have a package that references a previous HotChocolate version? If so update it to 13.2

**Comment by bensmind** [comment]
@michaelstaib thanks! I bumped all packages to 13.2.1 and it now appears everything is working as expected.
