### ISSUE TITLE
RabbitMQ subscriptions do not ensure topics exists before publishing messages

### ISSUE THREAD

**Issue by Alexanerinova** [ChilliCream/graphql-platform#6260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When sending a message to a topic while using the new `HotChocolate.Subscriptions.RabbitMQ` library (Version 13.2.1) before the first subscriber connects, the `RabbitMQPubSub` (or `DefaultPubSub`) do not ensure the topic is created first. At least for RabbitMQ this leads to an error. 

**Expected behavior**: The topic is created before sending the first message to it, like it is done when creating the first subscription.

### Steps to reproduce

1. Ensure your RabbitMQ instance is clean, and the `Exchange` you try to reproduce this issue on does not exist. 
   Easiest way might be to just use a new instance by starting a fresh docker container. 
2. Run a HotChocolate GraphQL server using the `HotChocolate.Subscriptions.RabbitMQ` library in version 13.2.1. 
3. Add a subscription with at least one topic on your GraphQL schema.
4. Create a `BackgroundService` which continuously sends messages to that topic. 
5. Run the application and ensure that nothing tries to subscribe to that topic. 
6. Wait for the `BackgroundService` to fail. 

**Result**
An exception occurs indicating, that the RabbitMQ exchange does not exist. 

**Description**
In the code, the exchange declaration is happening in the `CreateConsumer` method of the `RabbitMQTopic<TMessage>` class. However, this method is called from within the `OnConnectAsync` method, which is executed when a consumer connects to the topic. Since nothing tried to connect to the topic yet, and we are encountering the exception while publishing a message, the exchange has not been declared yet, and thus publishing messages onto leads to the described error.

### Relevant log output

```shell
RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text='NOT_FOUND - no exchange '9F3CF21C14756A67658267B93AEC3A7C' in vhost '/'', classId=60, methodId=40
   at RabbitMQ.Client.Impl.SessionBase.Transmit(OutgoingCommand& cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, ReadOnlyMemory`1 body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, ReadOnlyMemory`1 body)
   at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, ReadOnlyMemory`1 body)
   at RabbitMQ.Client.Impl.AutorecoveringModel.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, ReadOnlyMemory`1 body)
   at HotChocolate.Subscriptions.RabbitMQ.RabbitMQPubSub.PublishAsync(String formattedTopic, String message)
   at HotChocolate.Subscriptions.RabbitMQ.RabbitMQPubSub.OnSendAsync[TMessage](String formattedTopic, TMessage message, CancellationToken cancellationToken)
   at GraphQLTest.ExampleService.ExampleBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\dev\GraphQLTest\src\Auex.ExampleService\ExampleBackgroundService.cs:line 21
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

### Additional Context?

Ensure your RabbitMQ instance is clean, and the `exchange` you try to reproduce this issue on does not exist. Easiest way might be to just use a new instance by starting a fresh docker container. 

### Version

13.2.1

**Comment by dnetguru** [comment]
I'm experiencing the same problem. I took quick look and it seems that the exchange is declared as part of [OnConnectAsync](https://github.com/ChilliCream/graphql-platform/blob/388f5c988bbb806e46e2315f1844ea5bb63096f2/src/HotChocolate/Core/src/Subscriptions.RabbitMQ/RabbitMQTopic.cs#L70C1-L74C32).

Does it not make more sense to create the exchange during `CreateTopicAsync`?

**Comment by michaelstaib** [comment]
Hey,

I have tested this on main.

What I tested:

```csharp
[Fact]
public async Task Publish_Before_First_Subscription_Does_Not_Throw()
{
    var topic = $"issue-6260-{Guid.NewGuid():N}";

    await using var sender = await CreateRabbitTopicEventSenderAsync();

    // Publish before any subscriber exists (same pattern as the issue)
    for (var i = 0; i < 20; i++)
    {
        await sender.SendAsync(topic, $"event-{i}");
    }

    // Assert: no exception was thrown while publishing early
}
```

Result: I could not reproduce the issue on main. Early publish worked without throwing.
