### ISSUE TITLE
System.NullReferenceException CacheDataLoader

### ISSUE THREAD

**Issue by Scott-Selke** [ChilliCream/graphql-platform#6280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Since Upgrading my HC version to `13.2.1` from HC version `11.3.8` I have noted that periodically some dataloaders ( specifically ones using `CacheDataLoader` fail with a `System.NullReferenceException`. There seems to be no obvious pattern for when the errors appear. Data validation for incoming requests has been completed and I have narrowed down the issue to the data loaders themselves. 

### Steps to reproduce

1. Create a cacheDataLoader
2. Randomly will fail every 20 or so calls.

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at REDACTED(IResolverContext context, Guid caseReviewId) in /app/REDACTED/CachedDataService.cs:line 241
   at REDACTED(ICachedDataService cachedDataService, ISalesforceVerificationsGateway salesforceService, IResolverContext context) in /app/REDACTED.cs:line 66
   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)
   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Additional Context?

The stack trace references an interface of ICachedDataService. This is a service class that has some DI for my external services, and has various methods that take in a `IResolvedContext` from my presentation layer. The only dataloaders that fail are CacheDataLoaders.

### Version

13.2.1

**Comment by Scott-Selke** [comment]
Additional comment - it appears after more investigation that the failures happen when two nodes call the same cacheDataLoader at the same time. Their exception timestamp is the same down to the millisecond.

**Comment by YuvalHelman** [comment]
Having this issue too.
Using `BatchDataLoader`, and two different Resolvers within the same query call the same cached keys, and 1 out of 3 queries fails with the same Error.

@michaelstaib @Scott-Selke any advances on solving the issue?

**Comment by michaelstaib** [comment]
Are you using the `IResolverContext` in the DataLoader? The resolver context is a rented object and is not supposed to be used within a DataLoader.
