### ISSUE TITLE
Unable to resolve type reference `[Position]`. (HotChocolate.Types.InputObjectType) with spatial data using fusion gateway

### ISSUE THREAD

**Issue by FairyFox5700** [ChilliCream/graphql-platform#6336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am trying to use spatial types in gateway layer, but receiving the error described below

My schema, the other types are from demo and have not been changed by me.
```
[Table("Users")]
public class Author
{
    [Key]
    public int Id { get; set; }

    [Required]
    [MaxLength(128)]
    public string? Name { get; set; }

    public Point Point { get; set; }

    public Polygon? Polygon { get; set; }

    public IList<Review> Reviews { get; set; } = new List<Review>();
}
```

I also had the same using stitching version 13.0.0
Is there any solution for this?

### Steps to reproduce

1. 1. Start with project https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/Fusion1
2. Add spatial types for the objects like this
```
    public Point Point { get; set; }

    public Polygon? Polygon { get; set; }
```
Add spatial types to graph ql server
`.AddSpatialTypes()`
3. Generate schema:
 dotnet run --project Subgraphs/Reviews -- schema export --output schema.graphql
4. Fusion pack:
dotnet fusion subgraph pack -w ./Subgraphs/Reviews
5. Fusion compose:
dotnet fusion  compose -p ./Gateway/gateway -s ./Subgraphs/Reviews

Note: I also used the SQL Server db connection
Dependencies:

```
	  <PackageReference Include="HotChocolate.Data.Spatial" Version="13.3.3" />
	  <PackageReference Include="HotChocolate.Types.Spatial" Version="13.3.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="7.0.9" />
	  <PackageReference Include="NetTopologySuite" Version="2.5.0" />
	  <PackageReference Include="HotChocolate.AspNetCore" Version="13.3.3" />
          <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="13.3.3" />
          <PackageReference Include="HotChocolate.Data.EntityFramework" Version="13.3.3" />
         <PackageReference Include="HotChocolate.Types.Analyzers" Version="13.3.3">
```

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `[Position]`. (HotChocolate.Types.InputObjectType)

   at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
   at HotChocolate.Types.InputField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, InputFieldDefinition definition)
   at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Types.FieldBase`1.HotChocolate.Types.Helpers.IFieldCompletion.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
   at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
   at HotChocolate.Types.InputObjectType.OnCompleteFields(ITypeCompletionContext context, InputObjectTypeDefinition definition)
   at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)
```

### Version

13.3.3

**Comment by MatthewMucker** [comment]
I'm seeing a similar error in my project. Michael, you've marked this as a 'bug' so hopefully you understand the root cause... what can I look for in my project to see if my issue is the same thing?

**Comment by michaelstaib** [comment]
I have not marked it as a bug ... I just set the fusion tag ... we gonna look into it.

**Comment by Jacob-Steentoft** [comment]
Hi.

We're seeing similar errors using Fusion for our solution when using `HotChocolate.Data.Spatial` types for version `14.2.0`:
```
      Connection id "0HN8M05ITP2NJ", Request id "0HN8M05ITP2NJ:00000004": An unhandled exception was thrown by the application.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to resolve type reference `[[Position]]`. (HotChocolate.Types.InputObjectType)

         at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
         at HotChocolate.Types.InputField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, InputFieldDefinition definition)
         at HotChocolate.Types.InputField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, FieldDefinitionBase definition)
         at HotChocolate.Types.FieldBase.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
         at HotChocolate.Types.FieldBase.HotChocolate.Types.Helpers.IFieldCompletion.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
         at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
         at HotChocolate.Types.InputObjectType.OnCompleteFields(ITypeCompletionContext context, InputObjectTypeDefinition definition)
         at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__33_0(RegisteredType type)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpGetMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpMultipartMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass23_0.<<UseCancellation>b__1>d.MoveNext()
```

Is there a workaround that can be applied?

**Comment by sprioc** [comment]
I have the same issue when using Noda time. In my subgraph I have

builder.AddType<InstantType>();

This runs fine, but when running the gateway using Fusion I get the error:

1. Unable to resolve type reference `Instant`. (HotChocolate.Types.ObjectType)

**Comment by rustam-ashurov-mcx** [comment]
@michaelstaib could you please explain what means "For now just use the core builder to add the scalar.". I have a similar issue in fusion gateway with "Unable to resolve type reference `FieldSet!`" and it's not my custom type, therefore I'm not sure how to register it in the gateway.

I think field set is this one type from schema:
```
directive @key(
  fields: **FieldSet**!
  resolvable: Boolean = true
) repeatable on OBJECT | INTERFACE
```

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `FieldSet!`. (HotChocolate.Types.DirectiveType)

   at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
   at HotChocolate.Types.Argument.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ArgumentDefinition definition)
   at HotChocolate.Types.Argument.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, FieldDefinitionBase definition)
   at HotChocolate.Types.FieldBase.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Types.FieldBase.HotChocolate.Types.Helpers.IFieldCompletion.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
   at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
   at HotChocolate.Types.DirectiveType.OnCompleteFields(ITypeCompletionContext context, DirectiveTypeDefinition definition)
   at HotChocolate.Types.DirectiveType.OnCompleteType(ITypeCompletionContext context, DirectiveTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__33_0(RegisteredType type)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateRequestExecutorAsync(String schemaName, Boolean isInitialCreation, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass23_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
```

**Comment by michaelstaib** [comment]
This one is now verified to be working with HotChocolate 16 without any extra registration.

**Comment by rustam-ashurov-mcx** [comment]
So just to avoid misunderstanding, @michaelstaib, the proposed solution is to move to preview of HotChocolate v16 (i.e. 16.0.0-p.11.14) ?
Also maybe a dummy question: are HotChocolate v16 preview nugget packages available on a nugget repo to be referenced?

**Update**, my bad, I was trying to update HotChocolate.Fusion but it's the only package from all we are using which has no preview version
