### ISSUE TITLE
System.ObjectDisposedException when using IDbContextFactory and IMemoryCache 

### ISSUE THREAD

**Issue by zulander1** [ChilliCream/graphql-platform#6342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Since our data does not change often, we are using IMemoryCache to cache the whole data. However, when the cache expires, we are getting System.ObjectDisposedException, we have implemented SemaphoreSlim to preventing multiple tread accessing this methods. 
Not sure why this is happening, is there something we forgot ? We followed this https://chillicream.com/docs/hotchocolate/v13/integrations/entity-framework

### Steps to reproduce

Extension
```
        public static void AddGraphQL(this IServiceCollection services)
        {
            services
            .AddGraphQLServer().AddFiltering<CustomFilteringConvention>().AddAuthorization()
            .AddQueryType(d => d.Name("Query"))
                .RegisterService<IEmployeeRepository>()
                .AddType<EmployeeQuery>()
                .AddType<EmployeeType>()
            .UseAutomaticPersistedQueryPipeline().AddInMemoryQueryStorage();
        }
```

EmployeeType
```
 public class EmployeeType : ObjectType<Employee>
    {
        protected override void Configure(IObjectTypeDescriptor<Employee> descriptor)
        {
            descriptor.Name("Employee");
            descriptor.Field(d => d.Name).Type<StringType>().Description("Name");
        }
    }

```

Query
```
    [ExtendObjectType("Query")]
    [Authorize]
    public class EmployeeQuery
    {
        private readonly IEmployeeRepository _employeeRepository;

        public EmployeeQuery(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }


        [UseOffsetPaging()]
        [UsePaging(IncludeTotalCount = true, MaxPageSize = 200)]
        [UseFiltering]
        public async Task<IEnumerable<Employee>> Employees()
        {
            return (await _employeeRepository.GetActiveEmployeesAsync()).Select(x => (Employee)x!);
        }
    }
```

Startup
```
builder.Services.AddGraphQL();
builder.Services.AddPooledDbContextFactory<EmployeeContext>(options => options.UseSqlServer(builder.Configuration.GetConnectionString(".."), x => x.EnableRetryOnFailure()));
builder.Services.AddTransient<IEmployeeRepository, EmployeeRepository>();
```

Repository
```
public class EmployeeRepository : IEmployeeRepository, IAsyncDisposable
    {
        private readonly ManagerContext _dbContext;
        private readonly IMemoryCache _memoryCache;
        private readonly SemaphoreSlim _semaphore = new(1, 1);

        public EmployeeRepository (IDbContextFactory<EmployeeContext> db, IMemoryCache memoryCache)
        {
            _dbContext = db.CreateDbContext();
            _memoryCache = memoryCache;
        }

        public async ValueTask DisposeAsync()
        {
            await _dbContext.DisposeAsync();
            GC.SuppressFinalize(this);
        }

 
        public async Task<IEnumerable<Employee>> GetActiveEmployeesAsync()
        {
            string cacheKey = "employeeCache";

            try
            {
                await _semaphore.WaitAsync();

                if (_memoryCache.TryGetValue(cacheKey, out IEnumerable<Employee>? employees))
                    return employees!;

                return await _memoryCache.GetOrCreateAsync(cacheKey, async x =>
                {
                    x.SlidingExpiration = TimeSpan.FromSeconds(10);

                    return await _dbContext.Employees.Where(x => x.IsActive).Select(x => new Employee()
                    {
                        Name = x.Name,
                    }).ToListAsync();
                }) ?? Enumerable.Empty<Employee>();
            }
            finally
            {
                _semaphore.Release();
            }
        }
    }
```

### Relevant log output

```shell
System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'EmployeeContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_Database()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.OnFirstExecution()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### Version

13.2.1

**Comment by zulander1** [comment]
Removing IAsyncDisposable and changing to _using_ this seem to be working:

From:
`return await _dbContext.Employees.Where(x => x.IsActive).Select(x => new Employee() ...`

To: 

```
using var context= _dbContext.CreateDbContext();
return await context.Employees.Where(x => x.IsActive).Select(x => new Employee()
```

**Comment by michaelstaib** [comment]
This is not a bug of HotChocolate.

**Comment by nkolchakov** [comment]
I have the same issue using `IDbContextFactory` instead of `DbContext` directly. 
Why does happen under the hood ? Is it something in the HC middleware ? Like disposing the dbcontext after we return the IQueryable, but later when projecting the result the context is no longer alive ?
