### ISSUE TITLE
Generated SortInputObject types don't inherit from bound runtime types

### ISSUE THREAD

**Issue by maxnatamo** [ChilliCream/graphql-platform#6422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I'm actually unsure whether this is expected behaviors or an elusive bug. Most classes here are auto-generated or defined in external libraries. If it is expected, is there any way to remedy this?

Given a single interface with only method(s) and matching implementation:
```cs
    public interface IEncodedString
    {
        string GetValue();
    }

    public class EncodedString : IEncodedString
    {
        /// <summary>
        /// Implementation is irrelavent.
        /// </summary>
        private string Value { get; } = string.Empty;
        
        public EncodedString(string value)
            => this.Value = value;

        public string GetValue() => this.Value;
    }
```
and a runtime bind to the `String` scalar, along with type converters:
```cs
builder.BindRuntimeType<IEncodedString, StringType>();
builder.AddTypeConverter<EncodedString, string>(x => x.GetValue());
builder.AddTypeConverter<string, EncodedString>(x => new(x));
```

then, any sorting done on any object containing `IEncodedString` makes the project throw, as seen on the log output below.

```cs
[UseSorting]
public IEnumerable<Result> GetResult() =>
    Enumerable.Repeat<Result>(new()
    {
        Value = new EncodedString("value")
    }, 10);
```

Filtering works, but it also creates custom types, instead of using `StringFilterObject` input objects.

### Steps to reproduce

Reproduction repository: [https://github.com/maxnatamo/SortInputObjectIssue](https://github.com/maxnatamo/SortInputObjectIssue)

### Relevant log output

```shell
1. InputObject `IHtmlEncodedStringSortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<Umbraco.Cms.Core.Strings.IHtmlEncodedString>)

   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Warmup.ExecutorWarmupService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at HumanRise_Umbraco.Program.Main(String[] args) in C:\Users\***\Program.cs:line 6
```

### Additional Context?

The generated schema correctly assumes the `String` type:
```graphql
type Query {
  result: [Result!]!
}

type Result {
  value: String!
}
```

> Although, only available when sorting was disabled.

### Version

13.4.0

**Comment by michaelstaib** [comment]
Sorting policies have their own runtime bindings ... 

```
.AddSorting(c => c.Bind...
```

Be sure to add defaults first

**Comment by FelixZY** [comment]
@michaelstaib I ran into this today as well. Could this please be clarified in the [documentation for sorting](https://chillicream.com/docs/hotchocolate/v13/fetching-data/sorting)?
