### ISSUE TITLE
Cannot add `AddAuthorization()` when a stitched schema also uses authorization

### ISSUE THREAD

**Issue by nibblesnbits** [ChilliCream/graphql-platform#6435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have a gateway project that users authorization and stitches another API that also uses authentication. The problem is, the overlaps in these directives cause an error on starting the gateway.

### Steps to reproduce

1. [Run this](https://github.com/nibblesnbits/AuthIssueDemo)

### Relevant log output

```shell
authissuedemo-graphql-gateway-1  | fail: Microsoft.Extensions.Hosting.Internal.Host[9]
authissuedemo-graphql-gateway-1  |       BackgroundService failed
authissuedemo-graphql-gateway-1  |       HotChocolate.SchemaException: For more details look at the `Errors` property.
authissuedemo-graphql-gateway-1  |
authissuedemo-graphql-gateway-1  |       1. The name `allowAnonymous` was already registered by another type. (HotChocolate.Types.DirectiveType)
authissuedemo-graphql-gateway-1  |
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeRegistry.Register(String typeName, RegisteredType registeredType)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.<CompleteNames>b__23_0(RegisteredType type)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.CompleteNames()
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.Initialize()
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.AspNetCore.Warmup.ExecutorWarmupService.ExecuteAsync(CancellationToken stoppingToken)
authissuedemo-graphql-gateway-1  |          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
authissuedemo-graphql-gateway-1  | crit: Microsoft.Extensions.Hosting.Internal.Host[10]
authissuedemo-graphql-gateway-1  |       The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
authissuedemo-graphql-gateway-1  |       HotChocolate.SchemaException: For more details look at the `Errors` property.
authissuedemo-graphql-gateway-1  |
authissuedemo-graphql-gateway-1  |       1. The name `allowAnonymous` was already registered by another type. (HotChocolate.Types.DirectiveType)
authissuedemo-graphql-gateway-1  |
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeRegistry.Register(String typeName, RegisteredType registeredType)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.<CompleteNames>b__23_0(RegisteredType type)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.CompleteNames()
authissuedemo-graphql-gateway-1  |          at HotChocolate.Configuration.TypeInitializer.Initialize()
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
authissuedemo-graphql-gateway-1  |          at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
authissuedemo-graphql-gateway-1  |          at HotChocolate.AspNetCore.Warmup.ExecutorWarmupService.ExecuteAsync(CancellationToken stoppingToken)
authissuedemo-graphql-gateway-1  |          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
authissuedemo-graphql-gateway-1  | info: Microsoft.Hosting.Lifetime[0]
authissuedemo-graphql-gateway-1  |       Application is shutting down...
authissuedemo-graphql-gateway-1 exited with code 0
```

### Version

13.4.0

**Comment by nibblesnbits** [comment]
Update: [this branch](https://github.com/nibblesnbits/AuthIssueDemo/tree/straight-stiching) might be a more "correct" way of doing this.  If so, just let me know.

**Comment by michaelstaib** [comment]
We are no longer supporting HotChocolate.Stitching as it has been replaced by HotChocolate.Fusion.
