### ISSUE TITLE
ResolveWith<> Fails when an interface is specified in 13.1+ As a Non Abstract Class is Required

### ISSUE THREAD

**Issue by williamdenton** [ChilliCream/graphql-platform#6440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

The changes implemented in the PR linked below have broken `ResolveWith<>` when using an Interface to specify the resolver. 

https://github.com/ChilliCream/graphql-platform/issues/6075
https://github.com/ChilliCream/graphql-platform/pull/6110

This pattern works in 12.x when using DI to resolve the correct implementation 
```cs
serviceCollection.AddTransient<IFooResolvers, FooResolvers>();
```

```cs

public interface IFooResolvers {
    string GetFoo(string arg)
}

public class FooResolvers : IFooResolvers
{
    public string GetFoo(string arg)
    {
        // Omitted code for brevity
    }
}

public class QueryType : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor
            .Field("foo")
            .Argument("arg", a => a.Type<NonNullType<StringType>>())
            .ResolveWith<IFooResolvers>(r => r.GetFoo(default));
    }
}
```

This is the exception that is thrown in my use case.

https://github.com/ChilliCream/graphql-platform/blob/d7b84630de9786bc0f73653970f5f6811fc181a8/src/HotChocolate/Core/src/Types/Types/Descriptors/ObjectFieldDescriptor.cs#L392-L403

Am I holding HotChocolate wrong by using DI/Interfaces to specify the resolver?

I note in the original issue this comment
>ResolveWith needs a non abstract class at its a resolver type that will be instantiated. https://github.com/ChilliCream/graphql-platform/issues/6075#issuecomment-1521431178

Locally in debug I can set a break point on this line and drag it over to skip this condition execution and the code runs successfully. This suggests a possible fix for this is to make the change below.
```diff
-if (resolverType?.IsAbstract is true)
+if (resolverType?.IsAbstract is true &&  resolverType?.IsInterface is false)
```

As I mentioned above, if I'm holding hotChocolate wrong and i'm off the golden path I can update my codebase to use concrete resolvers (but this isn't a small undertaking for me)

### Steps to reproduce

1. 

### Relevant log output

```shell
System.ArgumentException: The resolver type namespace.IThingResolver cannot be used, a non-abstract type is required. (Parameter 'resolverType')
   at HotChocolate.Types.Descriptors.ObjectFieldDescriptor.ResolveWithInternal(MemberInfo propertyOrMethod, Type resolverType)
   at HotChocolate.Types.Descriptors.ObjectFieldDescriptor.ResolveWith[TResolver](Expression`1 propertyOrMethod)
```

### Version

13.4

**Comment by michaelstaib** [comment]
I have to look at this again.

**Comment by williamdenton** [comment]
There are some pretty serious pitfalls to doing this wrong as outlined in the documentation here https://chillicream.com/docs/hotchocolate/v13/server/dependency-injection#constructor-injection

As I converted my codebase to best practice (not using interface in resolveWith, not using constructor injection) i came across some serious side effects of doing it wrong especially when it comes to injecting BatchDataLoader and CacheDataLoader.

Maybe an option for forcing people (like me) onto a safer path (I like to call it the "pit of success"), the generic type used in ResolveWith could have a generic constraint that blocks constructor injection? This might be a bit too aggressive/opinionated for some people though as you _could_ inject some singleton behaviours with the constructor. Or a Roslyn Analyser to detect incorrect api usage?

```cs
IObjectFieldDescriptor ResolveWith<TResolver>(
        Expression<Func<TResolver, object?>> propertyOrMethod) where TResolver : new()
```

**Comment by marius-klimantavicius** [comment]
We are using interfaces with expectation that `ResolveWith<T>(s=>s.Method(default, default, ...))` would be compiled to something like:

```
var service = context.Service<T>();
var arg1 = ...;
var arg2 = ...;
...
return service.Method(arg1, arg2, ...);
```

Would it be possible to provide a resolver method that does something like this if ResolveWith can only be used with non-abstract resolvers?

**Comment by PavelA85** [comment]
BUMP

**Comment by michaelstaib** [comment]
Hey,

I have tested this on main.

Current main commit: `38911022f4`.

What I tested:

```csharp
[Fact]
public void ResolveWith_Interface_ResolverType_Throws_NonAbstractType_Required()
{
    var exception = Record.Exception(
        () => SchemaBuilder.New()
            .AddQueryType(
                descriptor => descriptor
                    .Field("foo")
                    .Argument("arg", arg => arg.Type<NonNullType<StringType>>())
                    .ResolveWith<IFooResolvers>(resolver => resolver.GetFoo(default!)))
            .Create());

    Assert.IsType<SchemaException>(exception);
    Assert.Contains("non-abstract type is required", exception.Message);
}

public interface IFooResolvers
{
    string GetFoo(string arg);
}
```

Result:
- Current main still rejects interface resolver types in `ResolveWith<TResolver>` with `non-abstract type is required`.
- This matches current resolver-type constraints in `ObjectFieldDescriptor` (concrete resolver type required), so I could not verify this as an active regression.

**Comment by michaelstaib** [comment]
Closing as current expected behavior: ResolveWith<TResolver> requires a concrete resolver type and does not support interface resolver types.
