### ISSUE TITLE
Fusion Subgraph Compose InvalidCastException

### ISSUE THREAD

**Issue by ndejaco2** [ChilliCream/graphql-platform#6489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am trying to compose a subgraph into a fusion .fsp file with the following schema:

```
type Author {
    id: ID!
    reviews: ReviewConnection
}

type Book {
    id: ID!
    reviews: ReviewConnection
}

input CreateReviewInput {
    bookId: ID!
    reviewerId: ID!
    authorId: ID!
    comment: String!
    rating: Int!
}

input DeleteReviewInput {
    id: ID!
}

type Review {
    id: ID!
    bookId: ID!
    reviewerId: ID!
    authorId: ID!
    comment: String!
    rating: Int!
}

type ReviewConnection {
    items: [Review]
    nextToken: String
}


type Mutation {
    createReview(input: CreateReviewInput!): Review
    deleteReview(input: DeleteReviewInput!): Review
}

type Query {
    getReview(id: ID!): Review
    listReviews(limit: Int, nextToken: String): ReviewConnection
    queryReviewsByBook(bookId: ID!, limit: int, nextToken: String): ReviewConnection
    queryReviewsByReviewer(reviewerId: ID!, limit: int, nextToken: String): ReviewConnection
    queryReviewsByAuthor(authorId: ID!, limit: int, nextToken: String): ReviewConnection
}

schema {
    query: Query,
    mutation: Mutation
}
```

The config file is like the following:

```
{
    "subgraph": "reviews",
    "http": { "baseAddress": "https://<some-endpoint>/graphql" }
}
```

I am able to successfully pack the subgraph into reviews.fsp file. However, I am getting the following error when trying to compose the gateway fsp file:

 % dotnet fusion compose -p ./fusion-gateway/gateway.fgp -s ./lib/sourceApis/ReviewsService

```
Unhandled exception: System.InvalidCastException: Unable to cast object of type 'HotChocolate.Skimmed.MissingType' to type 'HotChocolate.Skimmed.ScalarType'.
   at HotChocolate.Fusion.Composition.Pipeline.ScalarTypeMergeHandler.MergeAsync(CompositionContext context, TypeGroup typeGroup, CancellationToken cancellationToken) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/MergeHandler/ScalarTypeMergeHandler.cs:line 29
   at HotChocolate.Fusion.Composition.Pipeline.MergeTypeMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/MergeTypeMiddleware.cs:line 50
   at HotChocolate.Fusion.Composition.Pipeline.EntityFieldDependencyMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/EntityFieldDependencyMiddleware.cs:line 20
   at HotChocolate.Fusion.Composition.Pipeline.MergeEntityMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/MergeEntityMiddleware.cs:line 26
   at HotChocolate.Fusion.Composition.Pipeline.PrepareFusionSchemaMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/PrepareFusionSchemaMiddleware.cs:line 50
   at HotChocolate.Fusion.Composition.Pipeline.EnrichEntityMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/EnrichEntityMiddleware.cs:line 64
   at HotChocolate.Fusion.Composition.Pipeline.ApplyRemoveDirectiveMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/ApplyRemoveDirectiveMiddleware.cs:line 29
   at HotChocolate.Fusion.Composition.Pipeline.ApplyRenameDirectiveMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/ApplyRenameDirectiveMiddleware.cs:line 36
   at HotChocolate.Fusion.Composition.Pipeline.RegisterClientsMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/RegisterClientsMiddleware.cs:line 43
   at HotChocolate.Fusion.Composition.Pipeline.ParseSubgraphSchemaMiddleware.InvokeAsync(CompositionContext context, MergeDelegate next) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/Pipeline/ParseSubGraphSchemaMiddleware.cs:line 34
   at HotChocolate.Fusion.Composition.FusionGraphComposer.TryComposeAsync(IEnumerable`1 configurations, FusionFeatureCollection features, CancellationToken cancellationToken) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/Composition/FusionGraphComposer.cs:line 164
   at HotChocolate.Fusion.CommandLine.Commands.ComposeCommand.ExecuteAsync(IConsole console, FileInfo packageFile, List`1 subgraphPackageFiles, FileInfo settingsFile, DirectoryInfo workingDirectory, Nullable`1 enableNodes, CancellationToken cancellationToken) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/CommandLine/Commands/ComposeCommand.cs:line 179
   at HotChocolate.Fusion.CommandLine.Commands.ComposeCommand.ExecuteAsync(IConsole console, FileInfo packageFile, List`1 subgraphPackageFiles, FileInfo settingsFile, DirectoryInfo workingDirectory, Nullable`1 enableNodes, CancellationToken cancellationToken) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Fusion/src/CommandLine/Commands/ComposeCommand.cs:line 202
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Any idea what I am doing wrong?

### Steps to reproduce

1. Create a folder with above schema file and subgraph config. 
2. dotnet tool restore (Note, I am using HotChocolate.Fusion.CommandLine version 13.6.0-preview.2)
4. dotnet fusion subgraph pack -w ./lib/sourceApis/ReviewsService
5. dotnet fusion compose -p ./fusion-gateway/gateway.fgp -s ./appsync-infrastructure/lib/sourceApis/ReviewsService

### Version

13.6.0-preview.2

**Comment by ndejaco2** [comment]
The issue was a typo, input argument was int rather than Int :)

**Comment by michaelstaib** [comment]
Was at a conference in Copenhagen and could not answer... yes ... for 13.6 we are focusing on the validation story to have better errors.

**Comment by michaelstaib** [comment]
#6493
