### ISSUE TITLE
Unable to resolve type reference that is only in ErrorType

### ISSUE THREAD

**Issue by sunghwan2789** [ChilliCream/graphql-platform#6605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I tried to use mutation error configuration in HC 13.6 preview 31, but an error occured on fetching schema:

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to resolve type reference `Int32! (Output)`. (HotChocolate.Types.ErrorObjectType<CustomError>)

         at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
         at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
         at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
         at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
         at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
         at HotChocolate.Types.ObjectType.OnCompleteFields(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetSchemaAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpGetMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpMultipartMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass19_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Steps to reproduce

```cs
using HotChocolate;
using HotChocolate.Types;
using HotChocolate.Types.Descriptors;
using HotChocolate.Types.Descriptors.Definitions;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddGraphQLServer()
    .AddMutationConventions()
    .AddMutationErrorConfiguration<CustomErrorConfig>()
    .AddQueryType<Query>()
    .AddMutationType<Mutation>()
    ;

var app = builder.Build();

app.MapGraphQL();

app.Run();

class CustomErrorConfig : MutationErrorConfiguration
{
    public override void OnConfigure(IDescriptorContext context, ObjectFieldDefinition mutationField)
    {
        mutationField.AddErrorType(context, typeof(CustomError));
        mutationField.MiddlewareDefinitions.Add(new(next => async ctx => {
            try {
                await next(ctx);
            } catch (Exception ex) {
                ctx.Result = new MutationError(new CustomError(1, ex.Message));
            }
        }));
    }
}

public record CustomError(int ErrorCode, string Message);

public class Query {
    public Foo GetFoo() => new("Baz");
}

public class Mutation {
    public Foo AddFoo() {
        throw new Exception("foo");
    }
}

public record Foo(string Bar);
```

### Additional Context?

When `Foo` is changed to include `int` field, the exception is gone:

```cs
public record Foo(string Bar, int Baz = 1);
```

### Version

13.6.0-preview.31

**Comment by michaelstaib** [comment]
Good Catch! I will do a fix tomorrow.

**Comment by michaelstaib** [comment]
We will fix that in the next release ... towards the end of this year.

**Comment by eddex** [comment]
I have a similar issue to this, at least the error seems to be the same. If this is not the same issue, I can create a new issue.

Here's what I have:

Installed packages:
- HotChocolate/13.7.0
- HotChocolate.AspNetCore/13.7.0

```cs
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddGraphQLServer()
    .AddMutationConventions()
    .AddQueryType<Query>()
    .AddMutationType<Mutation>()
    ;

var app = builder.Build();

app.MapGraphQL();

app.Run();

public class Query {
    public Foo GetFoo() => new("Baz");
}

public class Mutation {

    [Error(typeof(CustomException))]
    public Foo AddFoo() {
        throw new CustomException();
    }
}

public record Foo(string Bar);

public class CustomException : Exception
{
    public ErrorDetail[] ErrorDetails { get; }

    public CustomException(params ErrorDetail[] errorDetails)
    {
        ErrorDetails = errorDetails;
    }
}

public class ErrorDetail
{
    public ErrorDetail(ErrorReason reason)
    {
        Reason = reason;
    }
    public ErrorReason Reason { get; }
}

public enum ErrorReason { A, B, C, }
```

When I run it and try to make a GraphQL request (query or mutation), I get the following error:
```log
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `[ErrorDetail!]! (Output)`. (HotChocolate.Types.ExceptionObjectType<CustomException>)

   at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
   at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
   at HotChocolate.Types.ObjectType.OnCompleteFields(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__30_0(RegisteredType type)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass19_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Am I mussing something during service registration or is this related to this issue? Or maybe even an unrelated issue?

**Comment by MasterJuan** [comment]
@michaelstaib any updates on this bug? Has been resolved?

**Comment by michaelstaib** [comment]
It's fixed in hc 14

**Comment by eddex** [comment]
> It's fixed in hc 14

So for anyone stuck with this issue when migrating from v12 to v13, do you suggest to just wait until v14 is out and then directly update from v12 to v14?
