### ISSUE TITLE
Method not found: 'System.Nullable`1<Boolean> HotChocolate.Configuration.ITypeCompletionContext.get_IsQueryType()'.'

### ISSUE THREAD

**Issue by CPVCZ** [ChilliCream/graphql-platform#6675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

After upgrading from 13.5.1 to 13.6.1 (We did not change anything else besides the version upgrade.) `IRequestExecutorResolver.GetRequestExecutorAsync` throws a `MissingMethodException` exception. 

Sadly we cannot investigate what part(s) of our configuration causes this issue because the exception is thrown from within HotChocolate. 

### Steps to reproduce

1. Upgrade from 13.5.1 to 13.6.1 
2. Call `IRequestExecutorResolver.GetRequestExecutorAsync`

### Relevant log output

```shell
System.MissingMethodException: Method not found: 'System.Nullable`1<Boolean> HotChocolate.Configuration.ITypeCompletionContext.get_IsQueryType()'.
     at HotChocolate.Data.Projections.ProjectionTypeInterceptor.OnAfterCompleteType(ITypeCompletionContext completionContext, DefinitionBase definition)
     at HotChocolate.Configuration.AggregateTypeInterceptor.OnAfterCompleteType(ITypeCompletionContext completionContext, DefinitionBase definition)
     at HotChocolate.Types.TypeSystemObjectBase`1.OnAfterCompleteType(ITypeCompletionContext context, DefinitionBase definition)
     at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
     at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
     at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__30_0(RegisteredType type)
     at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
     at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
     at HotChocolate.Configuration.TypeInitializer.Initialize()
     at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
     at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
     at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
     at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
     at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
```

### Version

13.6.1

**Comment by CPVCZ** [comment]
The issue seems to be that we did not upgrade `HotChocolate.Data.EntityFramework` to the same version. This issue can be considered as closed.
