### ISSUE TITLE
Error when exposing an object with a method returning an Expresion even when ignoring it

### ISSUE THREAD

**Issue by Yutsa** [ChilliCream/graphql-platform#6679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When exposing a class that has a public method returning a `Expression<Func<int, int>>` or any expression of func, a schema error will be thrown even if the method is ignored using an `ObjectTypeExtension`.

### Steps to reproduce

1. Create a class with a public method returning a `Expression<Func<int, int>>`
2. Create a query exposing this class
3. (Optional) Ignore the method using an `ObjectTypeExtension`
4. Try to get the schema using Banana Cake Pop or execute a query

### Relevant log output

```shell
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to infer or resolve a schema type from the type reference `Expression (Input)`.

         at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass19_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at ApiIdViniteca.Program.<>c.<<Main>b__7_9>d.MoveNext() in C:\Work\viniteca\app\Build\ApiIdViniteca2\Program.cs:line 267
      --- End of stack trace from previous location ---
         at ApiIdViniteca.Ressources.CustomMiddlewareResponse.InvokeAsync(HttpContext context) in C:\Work\viniteca\app\Build\ApiIdViniteca2\Ressources\CustomMiddlewareResponse.cs:line 44
         at ApiIdViniteca.Ressources.CustomMiddlewareAuthorisation.InvokeAsync(HttpContext context) in C:\Work\viniteca\app\Build\ApiIdViniteca2\Ressources\CustomMiddlewareAuthorisation.cs:line 185
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Additional Context?

Reproducible context : 

```
[ExtendObjectType<Query>]
public class TestQuery
{
    public List<TestClass> GetTestQuery()
    {
        return new List<TestClass>()
        {
            new TestClass()
            {
                Information = "Hello"
            }
        };
    }
}

public class TestClass
{
    public string Information { get; set; }

    public string ASimpleMethod()
    {
        return "Simple";
    }

    public Expression<Func<int, int>> ComplexMethod()
    {
        return t => t + 1;
    }
}

public class TestClassExtension : ObjectTypeExtension<TestClass>
{
    protected override void Configure(IObjectTypeDescriptor<TestClass> descriptor)
    {
        descriptor.Ignore(t => t.ComplexMethod());
    }
}
```

### Version

13.7.0

**Comment by michaelstaib** [comment]
Use ObjectType instead of ObjectTypeExtension.
