### ISSUE TITLE
HotChocolate causes dotnet 8 Blazor application to be incompatible with hot-reload

### ISSUE THREAD

**Issue by zaneclaes** [ChilliCream/graphql-platform#6695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I never before had any problems with `dotnet watch run` and Hot Chocolate. Now, each time I save any file, the entire server needs to be restarted because the HotChocolate type inspector "has already been marked as initialized" (see logs).

This is also a relatively new project, which was created fresh with the new Blazor "Web App" template. It is 100% reproducible in this context, as well as in a new template app.

### Steps to reproduce

1. Create a Dotnet 8 Blazor "Web App" (the new template style with mixed client/server rendering)
2. Add a basic hot chocolate schema to server
3. (Optional) you may need to also add a Wasm app that is client side rendered, I'm not sure if this is what is breaking it
4. Start the server with `dotnet watch run`
5. Save one of the code-first schema files to trigger hot reload

### Relevant log output

```shell
dotnet watch ⌚ File changed: ./Work/WorkMutations.cs.
[15:45:22 INF] Request starting HTTP/1.1 POST http://localhost:5292/_framework/blazor-hotreload - application/json 6440
[15:45:22 INF] Request finished HTTP/1.1 POST http://localhost:5292/_framework/blazor-hotreload - 200 0 null 4.5365ms
dotnet watch 🔥 Hot reload of changes succeeded.
[15:45:22 INF] Request starting HTTP/1.1 GET http://localhost:5292/scales - null null
[15:45:22 INF] Executing endpoint '/scales (/scales)'
[15:45:22 INF] Executed endpoint '/scales (/scales)'
[15:45:22 INF] HTTP GET /scales responded 200 in 5.1593 ms
[15:45:22 INF] Request finished HTTP/1.1 GET http://localhost:5292/scales - 200 null text/html; charset=utf-8 5.803ms
System.InvalidOperationException: The convention TuneDataTypeInspector has already been marked as initialized.
   at HotChocolate.Types.Descriptors.Convention.MarkInitialized()
   at HotChocolate.Types.Descriptors.Convention.Initialize(IConventionContext context)
   at HotChocolate.Types.Descriptors.DescriptorContext.GetConventionOrDefault[T](Func`1 defaultConvention, String scope)
   at HotChocolate.Types.Descriptors.DescriptorContextConventionExtensions.GetConventionOrDefault[T](IDescriptorContext context, T defaultConvention)
   at HotChocolate.Types.Descriptors.DescriptorContext.get_TypeInspector()
   at HotChocolate.SchemaBuilder.Setup.CreateTypeReferences(SchemaBuilder builder, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at Tuneality.Web.Server.Work.WorkExtensions.ExecuteInternalApiCall(IQueryRequestBuilder req, ITuneContext context)
   at Tuneality.Web.Server.Work.WorkDispatcher.Dispatch(String func, TimeSpan dt)
   at Tuneality.Web.Server.Work.WorkDispatcher.RunTask(TimeSpan dt)
   at Tuneality.Core.Lib.Utils.Tasks.<>c__DisplayClass3_0`1.<<ForeverLoop>b__0>d.MoveNext() in 
```

### Additional Context?

My data type inspector is very simple:

```
public class TuneDataTypeInspector : DefaultTypeInspector {
  public override bool IsMemberIgnored(MemberInfo member) {
    return base.IsMemberIgnored(member) || member.IsDefined(typeof(ApiIgnoreAttribute));
  }
}
```

### Version

14.0.0-r7

**Comment by zaneclaes** [comment]
@michaelstaib here's a minimal repro, with a brand new template app on version `14.0.0-p9`. It's only about 10 lines of code added to the template. To repro, just `dotnet watch run`, open a browser to execute a GraphQL request, then make a change to `Query.cs` to trigger hot reload, and try again:

[BlazorApp1.zip](https://github.com/ChilliCream/graphql-platform/files/13338260/BlazorApp1.zip)

First try:
<img width="1156" alt="Screenshot 2023-11-13 at 10 03 45 AM" src="https://github.com/ChilliCream/graphql-platform/assets/2084821/8e99c007-96be-4abc-bb3c-d74ff984350b">

After a hot-reload:
<img width="1848" alt="Screenshot 2023-11-13 at 10 02 03 AM" src="https://github.com/ChilliCream/graphql-platform/assets/2084821/e92059ca-ee20-47b5-b7dc-0b183ec3d8b5">

**Comment by zaneclaes** [comment]
@michaelstaib I've found a work-around that is sucessful about 80% of the time (better than nothing, but still not very workable).  My "fix" appears to demonstrate that the `System.InvalidOperationException` thrown by `MarkInitialized` is superfluous, but there must be some case it was designed for..? Is there a summary of why `Convention` cannot implement `MarkInitialized` idempotently?

```
public class TuneDataTypeInspector : DefaultTypeInspector {
  protected override void Initialize(IConventionContext context) {
    // do not call the base class, so it does not throw an exception.
  }
}
```

When the fix fails, the new error manifests as:
