### ISSUE TITLE
Getting IDBDatabase Error in Banana Cake Pop After Upgrade .NET and HotChocolate Versions

### ISSUE THREAD

**Issue by dmarciano** [ChilliCream/graphql-platform#6792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

We currently updated our GraphQL project from .NET 6 to .NET 8 and have started experiencing an issue when starting the application.  At the start of the day, everything was working fine and I worked on multiple incidents, however none of them required changes to GraphQL.

About an hour ago, I created a new branch off of our main code branch, made some GraphQL changes (to return an additional property), and when I started up the application Banana Cake Pop does not load, just the spinner is shown.  Checking the Chrome console I see the following error:
![image](https://github.com/ChilliCream/graphql-platform/assets/20006727/cee67a06-ec4f-40fe-83cc-b02c7224c788)

Thinking maybe I screwed something up, I switched back to the main code branch, which was working all morning, and I created several branches off of it which also worked fine, but even when I run the main branch now I still get the same issue.

However, two of my colleagues simply tried to run the main branch code (which was originally working for me) and immediately experienced this issue.  We are all running the same project and in the same environment setup:

.NET Version 8
Visual Studio Professional 17.8.3 
HotChocolate.AspNetCore 13.7.0
HotChocolate.AspNetCore.Authorization 13.7.0
Chrome Version 120.0.6099.129

### Steps to reproduce

Seems to happen in various way, but for my specific case:

1. Upgrade GraphQL project from .NET 6 to .NET 8
2. Upgrade HotChocolate.AspNetCore from 12.6.2 to 13.7.0
3. Upgrade HotChocolate.AspNetCore.Authorization from 12.14.0 to 13.7.0
4. Make changes to the GraphQL contracts (e.g., add a new property)
5. Run application to open Banana Cake Pop 

### Relevant log output

```shell
638.1bd26ed5.chunk.js:1 This app is being served cache-first by a service worker.
197.26a35fa9.js:2 Uncaught DOMException: Failed to execute 'deleteObjectStore' on 'IDBDatabase': The specified object store was not found.
    at Proxy.<anonymous> (https://localhost:7122/graphql/static/js/197.26a35fa9.js:2:342558)
    at migrateSchema (https://localhost:7122/graphql/static/js/main.3a5aa400.js:2:561850)
    at upgrade (https://localhost:7122/graphql/static/js/main.3a5aa400.js:2:566836)
    at IDBOpenDBRequest.<anonymous> (https://localhost:7122/graphql/static/js/431.a3ab1df2.js:2:4803074)
(anonymous) @ 197.26a35fa9.js:2
migrateSchema @ main.3a5aa400.js:2
upgrade @ main.3a5aa400.js:2
(anonymous) @ 431.a3ab1df2.js:2
IndexedDB (async)
o @ 431.a3ab1df2.js:2
(anonymous) @ main.3a5aa400.js:2
await in (anonymous) (async)
(anonymous) @ main.3a5aa400.js:2
ol @ 431.a3ab1df2.js:2
Sc @ 431.a3ab1df2.js:2
(anonymous) @ 431.a3ab1df2.js:2
C @ 431.a3ab1df2.js:2
T @ 431.a3ab1df2.js:2


197.26a35fa9.js:2 Uncaught (in promise) DOMException: Uncaught exception in event handler.
o @ 197.26a35fa9.js:2


graphql/:1 Uncaught (in promise) DOMException: Version change transaction was aborted in upgradeneeded event handler.
Promise.then (async)
(anonymous) @ main.3a5aa400.js:2
ol @ 431.a3ab1df2.js:2
Sc @ 431.a3ab1df2.js:2
(anonymous) @ 431.a3ab1df2.js:2
C @ 431.a3ab1df2.js:2
T @ 431.a3ab1df2.js:2
```

### Version

13.0.0
DB 19

**Comment by dmarciano** [comment]
I was able to find a work-around for this by going into the Developer Tools in Chrome and manually deleting the **banana-cake-pop** database from under _Application_ --> _Storage_ --> _IndexedDB_.  Is there any suggestion on what the root cause of this as we only updated to the latest packages, which I would not expect to break the database.

**Comment by rstaib** [comment]
It seems to be a cache hiccup. We couldn’t reproduce it, so we’re closing this issue. Feel free to reopen it if you find a way to reproduce the problem.
