### ISSUE TITLE
[Fusion] Graph generation issue with NetTopologySuite, InterfaceType and [UsePaging]

### ISSUE THREAD

**Issue by clintsinger** [ChilliCream/graphql-platform#6832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When generating a fusion graph if a query has the [UsePaging] attribute and returns an abstract type containing a type from NetTopologySuite (such as Point), the fusion graph compiler will throw the following error:

```
Unhandled exception: HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The type 'System.Byte*' may not be used as a type argument.
```

This error is common when a NTS type is returned directly in an HC type.  In this situation, there is an `InterfaceType` that should be handling it correctly but it seems when fusion is compiling it is ignoring this type in this situation.

### Steps to reproduce

1. Create the following classes
```
public abstract MyBaseClass
{
  public Guid Id { get; set; }
  public Point Position { get; set; }
}

public class MyInterfaceType : InterfaceType<MyBaseClass>
{
    protected override void Configure(IInterfaceTypeDescriptor<MyBaseClass> descriptor)
    {
        descriptor.BindFieldsExplicitly();
        descriptor.Field(p => p.Id);
    }
}

[QueryType]
public class MyQueries
{
  [UsePaging()]
  public async Task<Connection<MyBaseClass>> SomeQuery() => default;
}
```

2. Run the fusion graph generator
3. Observe the error
4. Remove the [UsePaging], or use a derived type as the return or remove the NTS type.
5. Run the fusion graph generator
6. Observe that the error is gone

### Relevant log output

```shell
Unhandled exception: HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The type 'System.Byte*' may not be used as a type argument.

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.CommandLine.ExportCommand.ExecuteAsync(IConsole console, IHost host, FileInfo output, String schemaName, CancellationToken cancellationToken)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.SyncUsingAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Version

14.0.0-p22

**Comment by michaelstaib** [comment]
Hey,

I have tested this on main.

What I tested:

- Retested at commit `38911022f4`.

```csharp
public class Issue6832ProbeTests
{
    [Fact]
    public void UsePaging_On_AbstractType_With_InterfaceType_And_Point_Does_Not_Throw()
    {
        var builder = SchemaBuilder.New()
            .AddQueryType<Query>()
            .AddType<MyBaseClassType>()
            .AddType<MyDerivedType>()
            .AddSpatialTypes();

        var exception = Record.Exception(builder.Create);

        Assert.Null(exception);
    }

    public abstract class MyBaseClass
    {
        public Guid Id { get; set; }
        public Point Position { get; set; } = default!;
    }

    public sealed class MyBaseClassType : InterfaceType<MyBaseClass>
    {
        protected override void Configure(IInterfaceTypeDescriptor<MyBaseClass> descriptor)
        {
            descriptor.BindFieldsExplicitly();
            descriptor.Field(x => x.Id);
        }
    }

    public sealed class MyDerivedType : ObjectType<MyDerived>
    {
        protected override void Configure(IObjectTypeDescriptor<MyDerived> descriptor)
        {
            descriptor.Implements<MyBaseClassType>();
            descriptor.BindFieldsExplicitly();
            descriptor.Field(x => x.Id);
        }
    }

    public sealed class Query
    {
        [UsePaging]
        public Task<Connection<MyBaseClass>> SomeQuery() =>
            Task.FromResult<Connection<MyBaseClass>>(default!);
    }

    public sealed class MyDerived : MyBaseClass;
}
```

This setup builds successfully on net8/net9/net10 and I could not reproduce the `System.Byte*` schema error on current `main`.

Closing this as not reproducible on current `main`.
