### ISSUE TITLE
StrawberryShake introspection failing when schema is formatted

### ISSUE THREAD

**Issue by tnestmann** [ChilliCream/graphql-platform#6851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

When running init or download with the StrawberryShake.Tools against a graph endpoint that returns the schema formatted the following error happens

```Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'String'.```

The schema was returned formatted (looks like in the code its called `Indented`). Not a HotChocolate server.
```
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "RootObject"
      },
...
```

After changing it to not formatted it works fine.
`{"data":{"__schema":{"queryType":{"name":"RootObject"},...`

Postman, Insomnia etc. seem to handle it regardless and 13.5.1 and earlier versions worked as well. Tried with latest code on main same issue.

### Steps to reproduce

1. Run `dotnet graphql init` against a server that will return schema formatted ("Indented").

### Relevant log output

```shell
Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'String'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
   at HotChocolate.Transport.OperationResult.Parse(JsonDocument document) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/AspNetCore/src/Transport.Abstractions/OperationResult.cs:line 80
   at HotChocolate.Transport.Http.GraphQLHttpResponse.ReadAsResultInternalAsync(String charSet, CancellationToken ct) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/AspNetCore/src/Transport.Http/GraphQLHttpResponse.cs:line 134
   at HotChocolate.Transport.Http.GraphQLHttpResponse.ReadAsResultInternalAsync(String charSet, CancellationToken ct) in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/AspNetCore/src/Transport.Http/GraphQLHttpResponse.cs:line 139
   at HotChocolate.Utilities.Introspection.CapabilityInspector.InspectSchemaAsync() in /home/runner/work/graphql-platform/graphql-platform/src/HotChocolate/Utilities/src/Utilities.Introspection/CapabilityInspector.cs:line 279
```

### Additional Context?

Might be related to the following test failing. `Serialize_Payload_Without_Extra_Whitespaces`
Output:
```
Xunit.Sdk.XunitException
The snapshot does not match:
  {
    "ContentType": "application/graphql-response+json; charset=utf-8",
    "StatusCode": "OK",
-   "Content": "{\n  \"data\": {\n    \"__typename\": \"Query\"\n  }\n}"
+   "Content": "{\r\n  \"data\": {\r\n    \"__typename\": \"Query\"\r\n  }\r\n}"
  }
```

### Version

13.8.1

**Comment by tnestmann** [comment]
Added a repo that shows the issue.
[Minimal replication repo](https://github.com/tnestmann/StrawberryShake-formatted-introspection)

**Comment by glen-84** [comment]
The `graphql-indented` endpoint isn't returning JSON.

```diff
-return Ok(result);
+return Content(result, "application/json");
```

**Comment by tnestmann** [comment]
Sorry about that. I should have caught that error.
I see that our server code has the same issue as the repository I created.
Thank you for reviewing it and catching that mistake. I should have noticed it earlier.
Sorry for taking up your time with this.

Closing.
