### ISSUE TITLE
Breaking Federation V1 support in 13.9.0 and up

### ISSUE THREAD

**Issue by EmilisM** [ChilliCream/graphql-platform#6966]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/EmilisM/hot-chocolate-v1-federations

### Steps to reproduce

1. Setting the `FederationVersion.Federation10` in `.AddApolloFederation` extension
2. Use directives and types supported by V1 Federations, `@key` throught `[Key]` attribute, `@external` through `[External]` attribute
3. Run the project and introspect or make a request

### What is expected?

The specified directives and types should be supported as per Federations V1 spec and are supported in version 13.8.1.

https://www.apollographql.com/docs/federation/federation-versions/#v10

### What is actually happening?

Exception is being thrown on runtime that `1. The following federation types were used and are not supported by the current federation version: @extends, @external, @key, FieldSet`

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The following federation types were used and are not supported by the current federation version: @extends, @external, @key, FieldSet

         at HotChocolate.ApolloFederation.FederationTypeInterceptor.RegisterImports()
         at HotChocolate.ApolloFederation.FederationTypeInterceptor.OnTypesCompletedName()
         at HotChocolate.Configuration.AggregateTypeInterceptor.OnTypesCompletedName()
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Additional context

I tried version `14.0.0-p.54` and the outcome was the same

**Comment by michaelstaib** [comment]
Thanks for reporting ... I will take a look.

**Comment by EmilisM** [comment]
Solved in 14.0.0, so closing this one.

**Comment by EmilisM** [comment]
Solved in 14.0.0, so closing this issue.
