### ISSUE TITLE
Your service provider may not support keyed services for HotChocolate.Stitching.Redis 13.9.0 in dotnet aspire

### ISSUE THREAD

**Issue by gpproton** [ChilliCream/graphql-platform#7029]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/gpproton/hotchocolate-aspire

## Environment:

windows 11
vscode
.NET 8.0 Aspire
webapi
redis

### Steps to reproduce

Added the line below after setting up dependent services.

```csharp
builder.Services
    .AddGraphQLServer()
    .AddQueryType(d => d.Name("Query"))
    .AddRemoteSchemasFromRedis("Demo", sp => sp.GetRequiredService<IConnectionMultiplexer>());
```

### What is expected?

To setup a graphql gateway using federation with Redis and this was working fine before dotnet aspire preview 4.

### What is actually happening?

The other services work fine except for the gateway service when using `AddRemoteSchemasFromRedis` for schema stitching.

### Relevant log output

```shell
Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRedisRequestExecutorBuilderExtensions.<>c.<AddRemoteSchemasFromRedis>b__0_2(ServiceDescriptor t)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRedisRequestExecutorBuilderExtensions.AddRemoteSchemasFromRedis(IRequestExecutorBuilder builder, String configurationName, Func`2 connectionFactory)
   at Program.<Main>$(String[] args) in D:\sandbox\hotchocolate-aspire\hotchocolate-aspire.ApiGateway\Program.cs:line 16
```

### Additional context

Alsoo tried with version 13.5.0 and above except 14.0.0 since no version is available for HotChocolate.Stitching.Redis

![Screenshot_28-3-2024_194924_localhost](https://github.com/ChilliCream/graphql-platform/assets/11395006/35d1b672-d2c4-42a5-bea2-b42226125dd2)
![Screenshot_28-3-2024_194947_localhost](https://github.com/ChilliCream/graphql-platform/assets/11395006/5180595c-f7d1-4dc2-b8cc-c1ecd05805d2)

**Comment by glen-84** [comment]
Stitching is deprecated in favour of `HotChocolate.Fusion`. We are no longer offering any fixes or updates for stitching. With version 14 we have removed the code and packages for stitching.
