### ISSUE TITLE
Schema first with type extension on querry

### ISSUE THREAD

**Issue by niklaskappler** [ChilliCream/graphql-platform#7313]
### Product

Hot Chocolate

### Version

"13.9.8

### Link to minimal reproduction

https://github.com/niklaskappler/chilli-cream-schema-first-with-type-extension

### Steps to reproduce

When using schema first approach my Query.cs file grows over 20 resolver functions and I try to split it into multiple chunks with type extension. But the types somehow do not get registered correctly or as I expect. How do I combine these correct?

```
builder.Services
    .AddGraphQLServer()
    .AddDocumentFromFile("schema.graphql")
    .AddTypeExtension<AuthorQuery>()
    .AddTypeExtension<BookQuery>()
    .BindRuntimeType<Book>()
    .BindRuntimeType<Author>();
```

with schema like 
```
type Query {
    book: Book
    author: Author
}

type Book {
    title: String
    author: Author!
}

type Author {
    name: String
}
```
and e.g.

```
[ExtendObjectType("Query")]
public class AuthorQuery
{
    [GraphQLName("author")]
    [GraphQLType("Author")]
    public Author Author() =>
        new Author()
        {
            Name = "Jon Skeet"
        };
}
```
    
    
    

### What is expected?

Expecting the application works the same as having only one Query.cs and register it with `.BindRuntimeType<Query>()`. 
For better readability I wanna split the file into chunks. 

### What is actually happening?

Actually when using this approach the models do get tried to register twice, even tough I remove the `.BindRuntimeType<Book>()` for example. 

```
 1. The name `Book` was already registered by another type. (HotChocolate.Types.ObjectType<SplitSchemaDemo.models.Book>)
```

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.
      
      1. The name `Book` was already registered by another type. (HotChocolate.Types.ObjectType<SplitSchemaDemo.models.Book>)
      
         at HotChocolate.Configuration.TypeRegistry.Register(String typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.<CompleteNames>b__23_0(RegisteredType type)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by michaelstaib** [comment]
```
builder.Services
    .AddGraphQLServer()
    .AddDocumentFromFile("schema.graphql")
    .BindRuntimeType<AuthorQuery>("Query")
    .BindRuntimeType<BookQuery>("Query")
    .BindRuntimeType<Book>()
    .BindRuntimeType<Author>();

public class AuthorQuery
{
    public Author Author() =>
        new Author()
        {
            Name = "Jon Skeet"
        };
}
 ```

**Comment by niklaskappler** [comment]
Hi @michaelstaib, 
I'm sorry to reopen this but the code snipped you provided is simply just not working.

 Registering two query types are just not working. You even put a hint in the [docs](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/queries) to use Type Extensions, bc AddQueryType can only register one query type. 
 
 
 How would you suggest to split up a huge Query file?
